var iv={INV_MTLS:2,INV_VERSION:4,INV_STRUCTURE:8,VIEW_TRANSITION:1,VIEW_UNDO:2,VIEW_INVALIDATE:4,VIEW_ANIM_SET:8,VIEW_ANIM_PLAY:16,VIEW_VISIBLE:32,VIEW_RESET_RCENTER:64,R_SELECTION:4,R_Z_NOWRITE:16,R_Z_OFFSET:0x30000,R_CLIP:0x1c0000,FILTER_LINEAR:1,FILTER_MIPMAP:2,FILTER_BOX:3,HIT_LAST:1,HIT_FULL:2,HIT_ALL:0x0ff00,HIT_ROOT:0x0100,HIT_CLIP:0x0200,HIT_GIZMO:0x0400,NS_VIS_THIS:1,NS_VIS_CHILDREN:2,NS_SELECTED:4,NS_CLOSED:8,NS_NOZWRITE:16,NS_NOHIT:64,NS_NOTREE:0x80,NS_CASTSHADOWS:0x100,NS_RCVSHADOWS:0x200,NS_NOXRAY: 0x40000,NS_NOCLIP:32,NS_MASK:16|32|0x70000|0x300,createRequest:function(f,p,cb){if(!f)return null;if(p)f=p+f;var r=new XMLHttpRequest(),u=f.toLowerCase(),c,l=u.indexOf("://");if(l>3 && l<8){p=location.origin.toLowerCase();l=p.length;c=(u.substring(0,l)!=p)&&("withCredentials" in r);}if(c)r.open("GET",f,true);else r.open("GET",f);r.onreadystatechange=function(){if((this.readyState==4)&&(this.status==200))cb(this);else
if(((this.status==404)||(this.status==0))&&this.onError)this.onError();};return r;},anim:{},indexOf:function(a,b){var c=a.length,i;for(i=0;i<c;i++){if(a[i]==b)return i;}return-1;},any:function(a,b){return(a==undefined)?b:a;},mtlChannels:["diffuse","specular","emissive","reflection","bump","opacity","lightmap"],isPOW2:function(v){return(v&(v-1))==0;},convertMatrix:function(a){var tm=mat4.identity(mat4.create()),k=0,i,j;for(i=0;i<4;i++)for(j=0;j<3;j++)tm[i*4+j]=a[k++];return tm;},getV:function(a,i,v){v[0]=a[i*3];v[1]=a[i*3+1];v[2]=a[i*3+2];},sp:function(e){if(e)e.stopPropagation();},pd:function(e){if(e && e.preventDefault)e.preventDefault();},pdsp:function(e){iv.pd(e);iv.sp(e);},stdViews:{left:{f:[-1,0,0],u:[-1,0,1]},right:{f:[1,0,0],u:[1,0,1]},front:{f:[0,-1,0],u:[0,-1,1]},back:{f:[0,1,0],u:[0,1,1]},top:{f:[0,0,1],u:[0,1,1]},bottom:{f:[0,0,-1],u:[0,-1,-1]}},abstract:function(){this.ref=0;},refSource:function(rc){;},ftoI:function(a){return Math.max(Math.min(Math.round(255*a),255),0);},f00:function(a){return[((a>>16)&0xff)/255,((a>>8)&0xff)/255,(a&0xff)/255];},parseColor:function(a,alpha){var c;switch(typeof a){case 'number':c=iv.f00(a);if(alpha)c[3]=((a>>24)&0xff)/255;break;case 'object':c=a.slice();break;case 'string':{var i=a.indexOf("rgba");if(i>=0){a=a.substr(i+4).trim();i=a.indexOf("("),j=a.lastIndexOf(")");if(i==0 && j>0){c=JSON.parse('['+a.substring(i+1,j)+']');if(c.length>=3 && c.length<=4){c[0]/=255;c[1]/=255;c[2]/=255;break;}}}
var i=a.indexOf("#");if(i>=0)c=iv.f00(parseInt(a.substr(i+1).trim(),16));}break;}if(!c)c=[1,1,1];if(alpha){if(c.length==3)c[3]=1.0;}else{if(c.length>3)c.splice(3);}return c;},isColor:function(a){return typeof a==='object';},getExtension:function(f){var e=f.substr(f.lastIndexOf('.')+1).toUpperCase();var i=e.indexOf('?');if(i>0)e=e.substring(0,index);return e;}};iv.refSource.prototype.refSourceName="source";iv.refSource.prototype.notify=function(a,b,def){var _i=this.refTargets,f,i;if(_i){b=b||{};b.code=a;b[this.refSourceName]=this;if(def)b.doDef=true;for(i=0;i<_i.length;i++){f=_i[i];if(f.onNotify)f.onNotify(b);else f(b);}return !def||b.doDef;}return true;}
iv.refSource.prototype.removeRefTarget=function(f){if(this.refTargets){var i=iv.indexOf(this.refTargets,f);if(i>=0){if(this.refTargets.length==1)this.refTargets=null;else this.refTargets.splice(i,1);return true;}}return false;}
iv.refSource.prototype.addRefTarget=function(f){if(!f)return false;if(this.refTargets){if(iv.indexOf(this.refTargets,f)>=0)return false;this.refTargets.push(f);}else this.refTargets=[f];return true;}
iv.makeRefSource=function(a){var b=iv.refSource.prototype;a.refSourceName=b.refSourceName;a.notify=b.notify;a.removeRefTarget=b.removeRefTarget;a.addRefTarget=b.addRefTarget;};iv.abstract.prototype=new iv.refSource();iv.abstract.prototype.destroy=function(){}
iv.abstract.prototype.addRef=function(){this.ref++;}
iv.abstract.prototype.release=function(){this.ref--;if(this.ref<1)this.destroy();}
glMatrixArrayType=typeof Float32Array!="undefined"?Float32Array:typeof WebGLFloatArray!="undefined"?WebGLFloatArray:Array;var vec3={},box3={},mat3={},mat4={},quat={};vec3.create=function(a){var b=new glMatrixArrayType(3);if(a){b[0]=a[0];b[1]=a[1];b[2]=a[2]}return b};vec3.set=function(a,b){b[0]=a[0];b[1]=a[1];b[2]=a[2];return b};vec3.add=function(a,b,c){if(!c||a==c){a[0]+=b[0];a[1]+=b[1];a[2]+=b[2];return a}c[0]=a[0]+b[0];c[1]=a[1]+b[1];c[2]=a[2]+b[2];return c};vec3.subtract=function(a,b,c){if(!c||a==c){a[0]-=b[0];a[1]-=b[1];a[2]-=b[2];return a}c[0]=a[0]-b[0];c[1]=a[1]-b[1];c[2]=a[2]-b[2];return c};vec3.scale=function(a,b,c){if(!c||a==c){a[0]*=b;a[1]*=b;a[2]*=b;return a}c[0]=a[0]*b;c[1]=a[1]*b;c[2]=a[2]*b;return c};vec3.normalize=function(a,b){b||(b=a);var c=a[0],d=a[1],e=a[2],g=Math.sqrt(c*c+d*d+e*e);if(g){if(g==1){b[0]=c;b[1]=d;b[2]=e;return b}}else{b[0]=0;b[1]=0;b[2]=0;return b}g=1/g;b[0]=c*g;b[1]=d*g;b[2]=e*g;return b};vec3.cross=function(a,b,c){c||(c=a);var d=a[0],e=a[1];a=a[2];var g=b[0],f=b[1];b=b[2];c[0]=e*b-a*f;c[1]=a*g-d*b;c[2]=d*f-e*g;return c};vec3.length=function(a){var b=a[0],c=a[1];a=a[2];return Math.sqrt(b*b+c*c+a*a)};vec3.dot=function(a,b){return a[0]*b[0]+a[1]*b[1]+a[2]*b[2]};vec3.distance=function(a,b){var c=b[0]-a[0],e=b[1]-a[1],d=b[2]-a[2];return Math.sqrt(c*c+e*e+d*d);}
vec3.cpy=function(dst,src){dst[0]=src[0];dst[1]=src[1];dst[2]=src[2];}
vec3.lerp=function(a,b,c,d){d=d||[];d[0]=a[0]+c*(b[0]-a[0]);d[1]=a[1]+c*(b[1]-a[1]);d[2]=a[2]+c*(b[2]-a[2]);return d;};vec3.compare=function(a,b,e){return(Math.abs(a[0]-b[0])<e)&&(Math.abs(a[1]-b[1])<e)&&(Math.abs(a[2]-b[2])<e);};vec3.crossN=function(a,b,c){return vec3.normalize(vec3.cross(a,b,c));};vec3.subtractN=function(a,b,c){return vec3.normalize(vec3.subtract(a,b,c));}
mat3.create=function(a){var b=new glMatrixArrayType(9);if(a){b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=a[3];b[4]=a[4];b[5]=a[5];b[6]=a[6];b[7]=a[7];b[8]=a[8];b[9]=a[9]}return b};mat3.identity=function(a){a[0]=1;a[1]=0;a[2]=0;a[3]=0;a[4]=1;a[5]=0;a[6]=0;a[7]=0;a[8]=1;return a};mat4.create=function(a){var b=new glMatrixArrayType(16);if(a){b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=a[3];b[4]=a[4];b[5]=a[5];b[6]=a[6];b[7]=a[7];b[8]=a[8];b[9]=a[9];b[10]=a[10];b[11]=a[11];b[12]=a[12];b[13]=a[13];b[14]=a[14];b[15]=a[15]}return b};mat4.identity=function(a){a[0]=1;a[1]=0;a[2]=0;a[3]=0;a[4]=0;a[5]=1;a[6]=0;a[7]=0;a[8]=0;a[9]=0;a[10]=1;a[11]=0;a[12]=0;a[13]=0;a[14]=0;a[15]=1;return a};mat4.m=function(b,a,c){c||(c=b);var d=a[0],e=a[1],g=a[2],f=a[3],h=a[4],i=a[5],j=a[6],k=a[7],l=a[8],o=a[9],m=a[10],n=a[11],p=a[12],r=a[13],s=a[14];a=a[15];var A=b[0],B=b[1],t=b[2],u=b[3],v=b[4],w=b[5],x=b[6],y=b[7],z=b[8],C=b[9],D=b[10],E=b[11],q=b[12],F=b[13],G=b[14];b=b[15];c[0]=A*d+B*h+t*l+u*p;c[1]=A*e+B*i+t*o+u*r;c[2]=A*g+B*j+t*m+u*s;c[3]=A*f+B*k+t*n+u*a;c[4]=v*d+w*h+x*l+y*p;c[5]=v*e+w*i+x*o+y*r;c[6]=v*g+w*j+x*m+y*s;c[7]=v*f+w*k+x*n+y*a;c[8]=z*d+C*h+D*l+E*p;c[9]=z*e+C*i+D*o+E*r;c[10]=z*
g+C*j+D*m+E*s;c[11]=z*f+C*k+D*n+E*a;c[12]=q*d+F*h+G*l+b*p;c[13]=q*e+F*i+G*o+b*r;c[14]=q*g+F*j+G*m+b*s;c[15]=q*f+F*k+G*n+b*a;return c};mat4.mulPointZ=function(a,b){var d=b[0],e=b[1];b=b[2];return a[2]*d+a[6]*e+a[10]*b+a[14];};mat4.mulPoint=function(a,b,c){c||(c=b);var d=b[0],e=b[1];b=b[2];c[0]=a[0]*d+a[4]*e+a[8]*b+a[12];c[1]=a[1]*d+a[5]*e+a[9]*b+a[13];c[2]=a[2]*d+a[6]*e+a[10]*b+a[14];return c};mat4.mulVector=function(a,b,c){c||(c=b);var d=b[0],e=b[1];b=b[2];c[0]=a[0]*d+a[4]*e+a[8]*b;c[1]=a[1]*d+a[5]*e+a[9]*b;c[2]=a[2]*d+a[6]*e+a[10]*b;return c};mat4.rotate=function(a,b,c,d){var e=c[0],g=c[1];c=c[2];var f=Math.sqrt(e*e+g*g+c*c);if(!f)return null;if(f!=1){f=1/f;e*=f;g*=f;c*=f}var h=Math.sin(b),i=Math.cos(b),j=1-i;b=a[0];f=a[1];var k=a[2],l=a[3],o=a[4],m=a[5],n=a[6],p=a[7],r=a[8],s=a[9],A=a[10],B=a[11],t=e*e*j+i,u=g*e*j+c*h,v=c*e*j-g*h,w=e*g*j-c*h,x=g*g*j+i,y=c*g*j+e*h,z=e*c*j+g*h;e=g*c*j-e*h;g=c*c*j+i;if(d){if(a!=d){d[12]=a[12];d[13]=a[13];d[14]=a[14];d[15]=a[15]}}else d=a;d[0]=b*t+o*u+r*v;d[1]=f*t+m*u+s*v;d[2]=k*t+n*u+A*v;d[3]=l*t+p*u+B*
v;d[4]=b*w+o*x+r*y;d[5]=f*w+m*x+s*y;d[6]=k*w+n*x+A*y;d[7]=l*w+p*x+B*y;d[8]=b*z+o*e+r*g;d[9]=f*z+m*e+s*g;d[10]=k*z+n*e+A*g;d[11]=l*z+p*e+B*g;return d};mat4.frustum=function(a,b,c,d,e,g,f){f||(f=mat4.create());var h=b-a,i=d-c,j=g-e;f[0]=e*2/h;f[1]=0;f[2]=0;f[3]=0;f[4]=0;f[5]=e*2/i;f[6]=0;f[7]=0;f[8]=(b+a)/h;f[9]=(d+c)/i;f[10]=-(g+e)/j;f[11]=-1;f[12]=0;f[13]=0;f[14]=-(g*e*2)/j;f[15]=0;return f};mat4.perspective=function(a,b,c,d,e){a=c*Math.tan(a);b=a*b;return mat4.frustum(-b,b,-a,a,c,d,e)};mat4.perspectiveEx=function(fov,k,near,far,tm){var d=(far-near)||0.1;d/=100;far+=d;near-=d;d=far/1000;if(near<d)near=d;return mat4.perspective(fov,k,near,far,tm);}
mat4.ortho=function(a,b,c,d,e,g,f){f||(f=mat4.create());var h=b-a,i=d-c,j=g-e;f[0]=2/h;f[1]=0;f[2]=0;f[3]=0;f[4]=0;f[5]=2/i;f[6]=0;f[7]=0;f[8]=0;f[9]=0;f[10]=-2/j;f[11]=0;f[12]=-(a+b)/h;f[13]=-(d+c)/i;f[14]=-(g+e)/j;f[15]=1;return f};mat4.lookAt=function(a,b,c,d){d||(d=mat4.create());var e=a[0],g=a[1];a=a[2];var f=c[0],h=c[1],i=c[2];c=b[1];var j=b[2];if(e==b[0]&&g==c&&a==j)return mat4.identity(d);var k,l,o,m;c=e-b[0];j=g-b[1];b=a-b[2];m=1/Math.sqrt(c*c+j*j+b*b);c*=m;j*=m;b*=m;k=h*b-i*j;i=i*c-f*b;f=f*j-h*c;if(m=Math.sqrt(k*k+i*i+f*f)){m=1/m;k*=m;i*=m;f*=m}else f=i=k=0;h=j*f-b*i;l=b*k-c*f;o=c*i-j*k;if(m=Math.sqrt(h*h+l*l+o*o)){m=1/m;h*=m;l*=m;o*=m}else o=l=h=0;d[0]=k;d[1]=h;d[2]=c;d[3]=0;d[4]=i;d[5]=l;d[6]=j;d[7]=0;d[8]=f;d[9]=o;d[10]=b;d[11]=0;d[12]=-(k*e+i*g+f*a);d[13]=-(h*e+l*g+o*a);d[14]=-(c*e+j*g+b*a);d[15]=1;return d};mat4.setScale=function(tm,s){tm[10]=tm[5]=tm[0]=s;}
mat4.offset=function(tm,a){tm[12]+=a[0];tm[13]+=a[1];tm[14]+=a[2];}
mat4.copy=function(src,dst){for(var i=0;i<16;i++)dst[i]=src[i];}
mat4.m_z=function(b,a,c){var g=a[2],j=a[6],m=a[10],s=a[14],A=b[0],B=b[1],t=b[2],u=b[3],v=b[4],w=b[5],x=b[6],y=b[7],z=b[8],C=b[9],D=b[10],E=b[11],q=b[12];c[2]=A*g+B*j+t*m+u*s;c[6]=v*g+w*j+x*m+y*s;c[10]=z*g+C*j+D*m+E*s;c[14]=q*g+b[13]*j+b[14]*m+b[15]*s;return c;};mat4.rotateAxisOrg=function(tm,org,axis,angle){var _org=[-org[0],-org[1],-org[2]];mat4.offset(tm,_org);var tmR=mat4.create(),tm2=mat4.create();mat4.identity(tmR);mat4.rotate(tmR,angle,axis);mat4.m(tm,tmR,tm2);mat4.copy(tm2,tm);mat4.offset(tm,org);return tm;}
mat4.setRow=function(tm,index,p){index*=4;tm[index]=p[0];tm[index+1]=p[1];tm[index+2]=p[2];};mat4.fromQuat=function(out,q){var x=q[0],y=q[1],z=q[2],w=q[3],x2=x+x,y2=y+y,z2=z+z,xx=x*x2,yx=y*x2,yy=y*y2,zx=z*x2,zy=z*y2,zz=z*z2,wx=w*x2,wy=w*y2,wz=w*z2;out[0]=1-yy-zz;out[1]=yx+wz;out[2]=zx-wy;out[3]=0;out[4]=yx-wz;out[5]=1-xx-zz;out[6]=zy+wx;out[7]=0;out[8]=zx+wy;out[9]=zy-wx;out[10]=1-xx-yy;out[11]=0;out[12]=0;out[13]=0;out[14]=0;out[15]=1;return out;};quat.slerp=function(out,a,b,t){var ax=a[0],ay=a[1],az=a[2],aw=a[3],bx=b[0],by=b[1],bz=b[2],bw=b[3],omega,cosom,sinom,scale0,scale1;cosom=ax*bx+ay*by+az*bz+aw*bw;if(cosom<0.0){cosom=-cosom;bx=-bx;by=-by;bz=-bz;bw=-bw;}if((1.0-cosom)> 0.000001){omega=Math.acos(cosom);sinom=Math.sin(omega);scale0=Math.sin((1.0-t)*omega)/sinom;scale1=Math.sin(t*omega)/sinom;}else{scale0=1.0-t;scale1=t;}
out[0]=scale0*ax+scale1*bx;out[1]=scale0*ay+scale1*by;out[2]=scale0*az+scale1*bz;out[3]=scale0*aw+scale1*bw;return out;};quat.fromMat4=function(out,m){var fTrace=m[0]+m[5]+m[10],fRoot;if(fTrace > 0.0){fRoot=Math.sqrt(fTrace+1.0);out[3]=0.5*fRoot;fRoot=0.5/fRoot;out[0]=(m[6]-m[9])*fRoot;out[1]=(m[8]-m[2])*fRoot;out[2]=(m[1]-m[4])*fRoot;}else{var i=(m[5]> m[0])?1:0;if(m[10]> m[i*4+i])i=2;var j=(i+1)%3,k=(i+2)%3;fRoot=Math.sqrt(m[i*4+i]-m[j*4+j]-m[k*4+k]+1.0);out[i]=0.5*fRoot;fRoot=0.5/fRoot;out[3]=(m[j*4+k]-m[k*4+j])*fRoot;out[j]=(m[j*4+i]+m[i*4+j])*fRoot;out[k]=(m[k*4+i]+m[i*4+k])*fRoot;}return out;};box3.size=function(b,v){if(!v)v=[];v[0]=b[3]-b[0];v[1]=b[4]-b[1];v[2]=b[5]-b[2];return v;}
box3.middle=function(b,v){if(!v)v=[];v[0]=(b[3]+b[0])/2;v[1]=(b[4]+b[1])/2;v[2]=(b[5]+b[2])/2;return v;}
iv.size=function(x,y){this.x=x||0;this.y=y||0};iv.size.prototype.set=function(x,y){if(this.x!=x||this.y!=y){this.x=x;this.y=y;return true;}return false;};iv.window=function(info){this.viewport=new iv.size();this.buffer=new iv.size();if(info.canvas){this.canvas=info.canvas;this.canvas.style['touch-action']='none';this.updateViewSize();}else this.canvas=null;if(info.callback)this.addRefTarget(info.callback);this.spaceId=0;this.view=new iv.viewInfo({from:[0,0,6],to:[0,0,0],up:[0,1,0],fov:90});this.cfgAutoSpin=1;this.cfgMouseDelta=2;this.cfgSpinSpeed=1.0;this.cfgOrbitMode=1;this.cfgButtons=[1,2,4];this.cfgMinDistance=1e-6;this.cfgMaxDistance=1e8;this.cfgMouseWheel=2;this.cfgBkColor=(info.color!==undefined)?info.color:0x7f7f7f;this.cfgResources="res/";this.clrSelection=[1,0,0,0.5,1,1];this.cfgXRayAlways=false;this.initHardware();this.vpVersion=0;this.structVersion=0;this.textures=[];this.imp={lastTouchDistance:-1,LY:0,LX:0,mouseMoved:false,mouseCancelPopup:false,mouseCaptured:false,numFrames:0};this.cfgRotateMouseHit=false;this.cfgAllowSelection=true;this.timer=false;this.postRepaint=false;if(this.gl){if(info.file)this.load(info.file,info);else this.space=null;this.gl.enable(this.gl.DEPTH_TEST);this.initHandlers();this.initEvents();this.invalidate();}if(window.performance && window.performance.now)this.getTickCount=function(){return window.performance.now();};else this.getTickCount=function(){var d=new Date();var time=d.getTime();return time;};this.rcontext=new iv.rcontext(this);this.layer=null;}
iv.window.prototype=new iv.refSource();iv.window.prototype.refSourceName="wnd";iv.window.prototype.getRoot=function(){return this.space?this.space.root:null;}
iv.window.prototype._uvs=function(a,b,c,d){var u=this.viewport.set(a,b);u|=this.buffer.set(c,d);if(u && this.gl)this.invalidate(iv.INV_VERSION);this.notify("viewsize");}
iv.window.prototype.updateViewSize=function(){var c=this.canvas,r=c.getBoundingClientRect();this._uvs(r.width,r.height,c.width,c.height);}
iv.window.prototype.setViewSize=function(w,h,bw,bh){var c=this.canvas;if(w&&h&&c){if(!bh)bh=h;if(!bw)bw=w;c.height=bh;c.width=bw;c.style.width=''+w+'px';c.style.height=''+h+'px';this._uvs(w,h,bw,bh);}}
iv.window.prototype.initHandlers=function(){var w=this,i={move:function(event){return w._onMouseMove(event);},down:function(event){return w.onMouseDown(event,false);},up:function(event){return w.onMouseUp(event,false);},dbl:function(event){return w._onDblClick(event);},touchstart:function(event){return w.onTouchStart(event);},touchcancel:function(event){return w.onTouchCancel(event);},touchend:function(event){return w.onTouchEnd(event,true);},touchmove:function(event){return w.onTouchMove(event);},pointerdown:function(event){return w.onPointerDown(event);},pointerup:function(event){return w.onPointerUp(event);},pointermove:function(event){return w.onPointerMove(event);},lostcapture :function(event){return w.onLostCapture(event);},menu:function(event){return w._onContextMenu(event);},wheel:function(event){w.onMouseWheel(event);},a:function(){w.animate();}};this.input=i;}
iv.window.prototype.initEvents=function(){var w=(/Firefox/i.test(navigator.userAgent))?"DOMMouseScroll":"mousewheel",c=this.canvas,i=this.input;this.setEvent(c,w,i.wheel);this.setEvent(c,"contextmenu",i.menu);this.setEvent(c,"selectstart",function(){return false;});if(window.PointerEvent && navigator.maxTouchPoints && navigator.maxTouchPoints > 1 && this.canvas.setPointerCapture){this.pointers=[];this.setEvent(c,"pointerdown",i.pointerdown);this.setEvent(c,"pointermove",i.pointermove);this.setEvent(c,"pointerup",i.pointerup);this.setEvent(c,"lostpointercapture",i.lostcapture)}else
{this.setEvent(c,"mousedown",i.down);this.setEvent(c,"mousemove",i.move);this.setEvent(c,"dblclick",i.dbl);this.setEvent(c,"touchstart",i.touchstart);}}
iv.window.prototype.releaseCapture=function(){if(this.imp.mouseCaptured){var e=this.canvas,i=this.input;if(e.releaseCapture)e.releaseCapture();else
{e=document;this.delEvent(e,"mousemove",i.move);this.delEvent(e,"contextmenu",i.menu);}this.delEvent(e,"mouseup",i.up);this.delEvent(e,"touchmove",i.touchmove);this.delEvent(e,"touchend",i.touchend);this.delEvent(e,"touchcancel",i.touchcancel);this.imp.mouseCaptured=false;}}
iv.window.prototype.checkRCenter=function(p){var I=this.imp,h=this.cfgRotateMouseHit;if(h){if(h.length==3)I.rCenter=h.slice();else{var h=this.hitTest(p);if(h)I.rCenter=h.pnt.slice();}}else I.rCenter=null;I.x0=p.x;I.y0=p.y;}
iv.window.prototype.setCapture=function(){if(!this.imp.mouseCaptured){var e=this.canvas,i=this.input;if(e.setCapture)e.setCapture();else
{e=document;this.setEvent(e,"mousemove",i.move);this.setEvent(e,"contextmenu",i.menu);}this.setEvent(e,"mouseup",i.up);this.setEvent(e,"touchmove",i.touchmove);this.setEvent(e,"touchend",i.touchend);this.setEvent(e,"touchcancel",i.touchcancel);this.imp.mouseCaptured=true;}}
iv.window.prototype.delEvent=function(d,e,f){if(d.detachEvent)d.detachEvent("on"+e,f);else if(d.removeEventListener)d.removeEventListener(e,f);}
iv.window.prototype.setEvent=function(d,e,f){if(d.attachEvent)d.attachEvent("on"+e,f);else if(d.addEventListener)d.addEventListener(e,f);}
iv.window.prototype.initHardware=function(){var r=null;if(window.requestAnimationFrame)r=window.requestAnimationFrame;else
if(window.webkitRequestAnimationFrame)r=window.webkitRequestAnimationFrame;else
if(window.mozRequestAnimationFrame)r=window.mozRequestAnimationFrame;else
r=function(callback){window.setTimeout(callback,1000/60)};this.requestAnimFrame=r;var n=["webgl","experimental-webgl","webkit-3d","moz-webgl"],cfg={alpha:false};for(var i=0;i<n.length;i++){try{this.gl=this.canvas.getContext(n[i],cfg);}catch(e){}if(this.gl)break;}if(!this.gl)this.notify("error",{type:"hardware",info:"Could not initialise WebGL"});return this.gl!=null;}
iv.viewInfo=function(v){this.from=[];this.to=[];this.up=[];this.ortho=false;this.scale=1;this.update(v);}
iv.viewInfo.prototype.update=function(f,t,u){if(f){if(t){vec3.cpy(this.from,f);vec3.cpy(this.to,t);vec3.cpy(this.up,u);}else{vec3.cpy(this.from,f.from);vec3.cpy(this.to,f.to);vec3.cpy(this.up,f.up);if(f.ortho){this.scale=f.scale;this.ortho=true;}
else
if(f.fov)this.fov=f.fov;if(f.bind)this.bind=f.bind;else this.bind='v';if(f.useNeighbours)this.useNeighbours=f.useNeighbours;this.camera=f.camera||null;}}}
iv.viewInfo.prototype.getUpVector=function(v){return vec3.subtract(this.up,this.from,v||[]);}
iv.viewInfo.prototype.getViewVector=function(v){return vec3.subtract(this.to,this.from,v||[]);}
iv.viewInfo.prototype.getViewVectorN=function(v){return vec3.subtractN(this.to,this.from,v||[]);}
iv.viewInfo.prototype.compare=function(v){return(vec3.compare(this.from,v.from,1e-6)&&vec3.compare(this.to,v.to,1e-6)&&vec3.compare(this.up,v.up,1e-6));}
iv.viewInfo.prototype.transform=function(tm){if(tm.length<12){vec3.add(this.to,tm);vec3.add(this.from,tm);vec3.add(this.up,tm);}else{mat4.mulPoint(tm,this.to);mat4.mulPoint(tm,this.from);mat4.mulPoint(tm,this.up);}}
iv.viewInfo.prototype.rotate=function(c,x,b){this.transform(mat4.rotateAxisOrg(mat4.identity([]),c,x,b));}
iv.window.prototype.getView=function(i){if(i)i.update(this.view);else i=new iv.viewInfo(this.view);if(i.camera)i.camera=null;return i;}
iv.transitionView=function(wnd,v,flags){this.transition=iv.easeInOut;this.type="view";this.wnd=wnd;this.old=wnd.getView();this.target=v;var c=this.current=new iv.viewInfo(null);c.bind=v.bind;c.fov=v.fov;c.scale=v.fov;c.ortho=v.ortho;if(flags)this.flags=flags;this.duration=600;this.tm=[];this.prepare(v);this.prepare(this.old);this._dir=[0,0,-1];this._up=[0,1,0];}
iv.transitionView.prototype.detach=function(wnd,f){if(f && this.flags && this.target.anim){f=wnd._playFavAnimation(this.target,(this.flags&(iv.VIEW_ANIM_SET|iv.VIEW_ANIM_PLAY)));if(f&iv.VIEW_INVALIDATE)wnd.invalidate();}}
iv.transitionView.prototype.prepare=function(v){v._dir=vec3.subtract(v.to,v.from,[]);v._dirLen=vec3.length(v._dir);v._up=vec3.subtract(v.up,v.from,[]);v._upLen=vec3.length(v._up);if(v._dirLen)vec3.scale(v._dir,1/v._dirLen);if(v._upLen)vec3.scale(v._up,1/v._upLen);var _from=[0,0,0],tm=mat4.lookAt(_from,v._dir,v._up,[]);mat4.invert(tm,tm);v._Q=quat.fromMat4([],tm);}
iv.transitionView.prototype.animate=function(k){var c=this.current,t=this.target,o=this.old,_k=1-k;if(k>0.999){vec3.cpy(c.from,t.from);vec3.cpy(c.to,t.to);vec3.cpy(c.up,t.up);c.fov=t.fov;if(t.scale)c.scale=t.scale;}else{vec3.lerp(o.to,t.to,k,c.to);var q=[],upL=t._upLen*k+o._upLen*_k,dirL=t._dirLen*k+o._dirLen*_k;quat.slerp(q,o._Q,t._Q,k);mat4.fromQuat(this.tm,q);mat4.mulVector(this.tm,this._dir,c.from);mat4.mulVector(this.tm,this._up,c.up);vec3.scale(c.from,-dirL);vec3.scale(c.up,upL);vec3.add(c.from,c.to);vec3.add(c.up,c.from);if(c.ortho)c.scale=t.scale*k+o.scale*_k;else
c.fov=t.fov*k+o.fov*_k;}this.wnd.setView(c);return 7;}
iv.window.prototype.isOrtho=function(){if(this.view && this.view.ortho)return true;return false;}
iv.window.prototype.setOrtho=function(b){var v=this.view;if(v.ortho==b)return false;var l=vec3.distance(v.from,v.to);if(b){v.scale=1.0/(l*Math.tan(Math.PI*v.fov/(360)));}else
{l*=v.scale;if(l>1e-6)v.fov=Math.atan(1/l)*360/Math.PI;}
v.ortho=b;this.invalidate(iv.INV_VERSION);return true;}
iv.window.prototype.getFOV=function(v){if(!v)v=this.view;var fov=v.fov*Math.PI/360;var sx=this.viewport.x/2,sy=this.viewport.y/2,bind=v.bind;if(bind=='max')bind=sx>sy?'h':'v';else
if(bind=='min')bind=sx<sy?'h':'v';if(bind=='h'){var d=sx/Math.tan(fov);fov=Math.atan(sy/d);}else
if(bind=='d'){var sxy=Math.sqrt(sx*sx+sy*sy);var d=sxy/Math.tan(fov);fov=Math.atan(sy/d);}return fov;}
iv.window.prototype._cmpViews=function(V,v){if(v.from && v.to && v.up){if(V.compare(v)){if(v.fov){if((V.fov!=v.fov)&& !V.ortho)return false;if(V.bind!=v.bind)return false;}else
if(v.scale){if(V.scale!=v.scale && V.ortho)return false;}else return false;return true;}}return false;}
iv.window.prototype.validateView=function(v,flags){var _dir=[],_up=v.getUpVector();vec3.normalize(_up);vec3.subtractN(v.to,v.from,_dir);var _dot=vec3.dot(_dir,_up);if(Math.abs(_dot)>1e-5){var a2=[],a1=[];vec3.crossN(_dir,_up,a2);vec3.crossN(_dir,a2,a1);_dot=vec3.dot(_up,a1);if(_dot<0)vec3.scale(a1,-1);vec3.add(v.from,a1,v.up);}}
iv.window.prototype.setView=function(V,flags){if(!V)return;var v=new iv.viewInfo(V);v.src=V;this.validateView(v,flags);if(flags===undefined)flags=0;V=this.view;if(V.camera &&(V.camera!=v.camera))V.camera=null;if(!this._cmpViews(V,v)){var _o=this.isOrtho()!=v.ortho;if(_o){if(iv.VIEW_TRANSITION){flags&=~iv.VIEW_TRANSITION;flags|=iv.VIEW_INVALIDATE;}if(v.scale)_o=false;else v.ortho=false;}if(flags&iv.VIEW_TRANSITION){this.stopAR();this.removeAnimationType("view",true);this.addAnimation(new iv.transitionView(this,v,flags));return;}
V.update(v);if(_o)this.setOrtho(!v.perspective);}if(flags&iv.VIEW_INVALIDATE)this.invalidate(iv.INV_VERSION);}
iv.window.prototype.setDefView=function(flags){this.stopAR();if(flags===undefined)flags=iv.VIEW_INVALIDATE|iv.VIEW_RESET_RCENTER;this.setView(this.space.view,flags);}
iv.window.prototype.load=function(file,d){var s=new iv.space(this,this.gl),w=this,ext=(d && d.type)?d.type:iv.getExtension(file),p={loaded:0,total:1};if(d && d.path)s.path=d.path;var f=function(R){w.space=s;if(ext=='IV3D')s.loadBin(R.response);else s.load(JSON.parse(R.responseText));w.imp.numFrames=0;w.setDefView();w.notify("dataReady",{space:s});};var r=iv.createRequest(file,s.path,f);r.onError=function(){w.notify("loadError",{url:this.responseURL,status:this.status})};if(ext=='IV3D'){r.responseType="arraybuffer";if(p){r.onprogress=function(e){if(e.lengthComputable){p.loaded=e.loaded;p.total=e.total;w.notify("progress",p);};};w.notify("progress",p)}};r.send();}
iv.window.prototype.getDoubleSided=function(){return this.space?this.space.cfgDbl:false;}
iv.window.prototype.setDoubleSided=function(b){if(this.space.cfgDbl!=b){var s=this.space;s.cfgDbl=b;s.invalidate();}}
iv.window.prototype.getMaterials=function(){return this.space?(this.space.cfgDefMtl==null):false;}
iv.window.prototype.setMaterials=function(b){var s=this.space;if(b){if(s.cfgDefMtl){s.cfgDefMtl.clear();s.cfgDefMtl=null;this.invalidate();}}else{if(!s.cfgDefMtl){var m=new iv.material(s);m.load({"diffuse":0xcccccc,"specular":0x808080,"ambient":0x050505,"phong":25.6});s.cfgDefMtl=m;this.invalidate();};}}
iv.window.prototype.getTextures=function(){return this.space?this.space.cfgTextures:false;}
iv.window.prototype.setTextures=function(b){if(this.space && this.space.cfgTextures!=b){this.space.cfgTextures=b;this.invalidate();}}
iv.window.prototype.setLights=function(l){var s=this.space;if(!s)return false;if(l){s.lights=l;s.stdLights=true;}else
{s.lights=[];s.stdLights=false;}this.invalidate(iv.INV_MTLS);}
iv.window.prototype.onMouseUp=function(event,touch){var ar=this.commonMouseUp1(),e=event;if(touch){if(event.touches.length)e=event.touches[0];else e=null;}
var p=this.getClientPoint(e,touch);p.b=1;if(!touch &&(event.button!==undefined))p.b=1<<event.button;this.commonMouseUp2(p,event,ar);this.releaseCapture();}
iv.window.prototype.commonMouseUp1=function(){var a=this.last,ar=this.cfgAutoSpin;if(a){if(ar&1){var dt=this.getTickCount()-a.t;if(dt<200){this.removeAnimationType("view");this.addAnimation(new iv.anim.spin(this,dt));ar=0;}}this.last=null;}return ar;}
iv.window.prototype.commonMouseUp2=function(p,event,ar){}
iv.window.prototype.getTouchDistance=function(t){if(t &&(t.length>1)){var dx=t[0].clientX-t[1].clientX,dy=t[0].clientY-t[1].clientY;return Math.sqrt(dx*dx+dy*dy);}return 0;}
iv.window.prototype.getClientPoint=function(e,touch){var r=this.canvas.getBoundingClientRect(),x=null,y=null,j,_e,l;if(e){x=e.clientX;y=e.clientY;if(touch && e.touches){l=e.touches.length;if(l){_e=e.touches[0];x=_e.clientX;y=_e.clientY;if(l>1){for(j=1;j<l;j++){_e=e.touches[j];x+=_e.clientX;y+=_e.clientY;}
x/=l;y/=l;}}}
x-=r.left;y-=r.top;}else{x=this.imp.LX;y=this.imp.LY;}return{x:x,y:y,r:r}}
iv.window.prototype.decodeButtons=function(e,bt){var btn=0;if(bt && e.touches!=undefined){if(e.touches.length>=3)return 4;return 1;}if(e.buttons===undefined){switch(e.which){case 2:btn=4;break;case 3:btn=2;break;default:btn=1;}}else btn=e.buttons;return btn;}
iv.window.prototype._onContextMenu=function(event){iv.pd(event);var I=this.imp;if(I.mouseCancelPopup&&I.mouseMoved){iv.sp(event);I.mouseCancelPopup=false;return false;}if(this.onContextMenu)this.onContextMenu(event);return true;}
iv.window.prototype._onDblClick=function(event){if(this.onDblClick)this.onDblClick(event,false);iv.pdsp(event);return true;}
iv.window.prototype.onTouchMove=function(event){var p=this.getClientPoint(event,true),t=event.touches;this.onMouseMove(event,p,t&&t.length>1?t:null,1);iv.pd(event);return false;}
iv.window.prototype.onTouchCancel=function(event){this.onMouseUp(event,true);if(event.cancelable)iv.pd(event);}
iv.window.prototype._onMouseMove=function(event){if(this.imp.mouseCaptured){var b=this.decodeButtons(event,false),p;if(b){p=this.getClientPoint(event,false);this.onMouseMove(event,p,null,b);}else this.onMouseUp(event,false);iv.pdsp(event);return true;}else{p=this.getClientPoint(event,false);p.b=0;this._onMouseHover(event,p);}return false;}
iv.window.prototype._onMouseHover=function(event,p){this.onMouseHover(event,p);}
iv.window.prototype.onMouseHover=function(event,p){if(!this.notify("mousehover",p,true))return 0;if(this.onMouseHoverGizmo)this.onMouseHoverGizmo(event,p);}
iv.window.prototype.getPointer=function(id,create){var _i=this.pointers,e,i;for(i=0;i<_i.length;i++){e=_i[i];if(e.id==id)return e;}if(create){_i.push(e={id:id});return e;}return null;}
iv.window.prototype.deletePointer=function(id){var _i=this.pointers,e,i;for(i=0;i<_i.length;i++){e=_i[i];if(e.id==id){_i.splice(i,1);return true;}}return false;}
iv.window.prototype.decodeButtonsPointer=function(event){if(event.pointerType=='mouse')return this.decodeButtons(event,false);return 1;}
iv.window.prototype.commonTouch=function(event){var p=this.getClientPoint(event,true),I=this.imp;I.LX=p.x;I.LY=p.y;I.lastTouchDistance=-1;I.mouseMoved=false;}
iv.window.prototype.onTouchEnd=function(event){if(!event.touches||!event.touches.length)this.onMouseUp(event,true);else this.commonTouch(event);if(event.cancelable)iv.pd(event);}
iv.window.prototype.checkDblTap=function(event){var t=this.getTickCount(),i=this.imp,r=true;if(this.onDblClick&&(i.lastTouchTime!==undefined)){var dt=(t-i.lastTouchTime);if(dt<500){this.onDblClick(event,true);t=undefined;r=false;}}
i.lastTouchTime=t;return r;}
iv.window.prototype.onTouchStart=function(event){var t=event.touches;if(t){if(((t.length==1)||(t.length>1 && !this.imp.mouseCaptured))){if(this.checkDblTap(event))this.onMouseDown(event,true);}else if(t.length>1 && this.imp.mouseCaptured)this.commonTouch(event);}}
iv.window.prototype.onPointerDown=function(event){if(!this.pointers||!this.pointers.length){if(!this.checkDblTap(event))return;}
var p=this.getClientPoint(event),id=event.pointerId,I=this.imp;p.b=this.decodeButtonsPointer(event);var ptr=this.getPointer(id,true);ptr.clientX=p.x;ptr.clientY=p.y;if(this.pointers.length==1){this.last={x:0,y:0,t:0};I.lastTouchDistance=-1;if(this.commonMouseDown1(p,event)){this.canvas.setPointerCapture(id);this.commonMouseDown2(p,event);}}}
iv.window.prototype.onPointerUp=function(event){iv.pdsp(event);if(event.pointerId){this.deletePointer(event.pointerId);this.canvas.releasePointerCapture(event.pointerId);}else this.pointers=[];if(!this.pointers.length){this.commonMouseUp1();var p=this.getClientPoint(event);p.b=this.decodeButtonsPointer(event);this.commonMouseUp2(p,event);}}
iv.window.prototype.onLostCapture=function(event){var _i=this.pointers,e,i,I=this.imp;if(event.pointerId){this.deletePointer(event.pointerId);if(_i.length){I.lastTouchDistance=-1;I.mouseMoved=false;e=_i[0];I.LX=e.clientX;I.LY=e.clientY;return;}}
for(i=0;i<_i.length;i++)this.canvas.releasePointerCapture(_i[i].id);this.pointers=[];this.commonMouseUp1();this.commonMouseUp2({x:10,y:10,b:1},event);}
iv.window.prototype.onPointerMove=function(event){iv.pdsp(event);var p=this.getClientPoint(event),ptr=this.getPointer(event.pointerId,false);if(ptr){ptr.clientX=p.x;ptr.clientY=p.y;}if(this.pointers.length){var ptr=this.pointers[0];this.onMouseMove(event,{x:ptr.clientX,y:ptr.clientY},this.pointers.length>1?this.pointers:null,this.decodeButtonsPointer(event));}
else{p.b=0;this._onMouseHover(event,p);}}
iv.window.prototype.onMouseDown=function(event,touch){var I=this.imp;this.last={x:0,y:0,t:0};I.lastTouchDistance=-1;if(touch){if(event.touches.length>1){I.lastTouchDistance=this.getTouchDistance(event.touches);}}
var p=this.getClientPoint(event,touch);p.b=this.decodeButtons(event,touch);if(this.commonMouseDown1(p,event)){this.setCapture();this.commonMouseDown2(p,event);}}
iv.window.prototype.commonMouseDown1=function(p,event){iv.pdsp(event);return true;}
iv.window.prototype.commonMouseDown2=function(p,event){var I=this.imp;this.stopAR();I.LX=p.x;I.LY=p.y;I.mouseMoved=false;}
iv.window.prototype.onMouseMove=function(event,p,touches,b){if(!this.notify("mousemove",{x:p.x,y:p.y,b:b},true))return;var d=this.cfgMouseDelta,I=this.imp,dX=p.x-I.LX,dY=p.y-I.LY,mv=(Math.abs(dX)>d)||(Math.abs(dY)>d),flags=3;if(mv)this.removeAnimationType("view",true);if(touches){var d=this.getTouchDistance(touches);if(I.lastTouchDistance!=d){if(I.lastTouchDistance>0){var _d=(I.lastTouchDistance-d)/2.0;this.doDolly(_d,_d);flags|=8;}
I.lastTouchDistance=d;}if(mv){this.doPan(dX,dY);flags|=8;}}else{if(I.mouseMoved||mv){p.b=b;b=this.mapButtonToNavigation(b,event);switch(b){case 1:
this.addIR(dX,dY,1);this.doOrbit(dX,dY);flags|=8;break;case 2:
if(!this.doDolly(dX,dY))return;flags|=8;break;case 3:
if(!this.doFOV(dX,dY))return;flags|=8;break;case 4:this.doPan(dX,dY);flags|=8;break;}}}this.onHandler(flags);I.mouseMoved|=mv;if(I.mouseMoved){I.LX=p.x;I.LY=p.y;}}
iv.window.prototype.mapButtonToNavigation=function(b,event){switch(b){case 1:b=this.cfgButtons[0];break;case 2:b=this.cfgButtons[1];this.imp.mouseCancelPopup=true;break;case 4:b=this.cfgButtons[2];break;default:b=0;}return b;}
iv.window.prototype.addIR=function(dX,dY,m){var a=this.last;if(a){a.x=dX+a.x/2;a.y=dY+a.y/2;var t=this.getTickCount();a.dt=t-a.t;a.t=t;a.mode=m;}}
iv.window.prototype.onHandler=function(flags){var invF=0;if(flags&8){flags|=2;invF=iv.INV_VERSION;}if(flags&16)invF|=iv.INV_STRUCTURE;if(flags&2)this.invalidate(invF);return(flags&1)?true:false;}
iv.window.prototype.onMouseWheel=function(event){var d;if(event.wheelDelta!=undefined)d=event.wheelDelta/-10;else
if(event.detail!=undefined){d=event.detail;if(d>10)d=10;else if(d<-10)d=-10;d*=4;}
switch(this.cfgMouseWheel){case 2:this.doDolly(0,d);break;case 3:this.doFOV(0,d);break;}this.invalidate(iv.INV_VERSION);iv.pd(event);}
iv.window.prototype.commonVPNotify=function(t,v,x,y){return{type:t,dX:x,dY:y,center:(this.imp.rCenter||v.to).slice()}};iv.window.prototype.isCustomCenter=function(i,v){return i.center && !vec3.compare(i.center,v.to,1e-8);}
iv.window.prototype.doPan=function(dX,dY){var v=this.getView(),i=this.commonVPNotify("pan",v,dX,dY),d;if(this.notify("camera",i,true)){if(this.isCustomCenter(i,v)){this.hcontext.update();var V=this.hcontext.worldToView(i.center,[]);V[0]+=dX;V[1]+=dY;d=vec3.subtract(i.center,this.hcontext.viewToWorld(V,[]),[]);}else{var x0=this.viewport.x/2,y0=this.viewport.y/2,r0=this.getRay(x0,y0),r1=this.getRay(x0-i.dX,y0-i.dY);d=[r1[3]-r0[3],r1[4]-r0[4],r1[5]-r0[5]];}
v.transform(d);this.setView(v);}}
iv.window.prototype.doOrbit=function(dX,dY){var v=this.getView(),i=this.commonVPNotify("orbit",v,dX,dY);if(this.notify("camera",i)){dX=-i.dX/200;dY=i.dY;var _u=v.getUpVector();if(dX && this.cfgOrbitMode){v.rotate(i.center,_u,dX);dX=0;}if(dY){vec3.normalize(_u);var _d=v.getViewVectorN(),_axis=vec3.cross(_d,_u,[]);var angle=dY/200.0;if(this.cfgMaxVAngle!=undefined){var viewAngle=Math.acos(Math.max(Math.min(vec3.dot(_d,[0,0,-1]),1),-1));var max=(90-this.cfgMinVAngle)*Math.PI/180,min=(90-this.cfgMaxVAngle)*Math.PI/180;dY=viewAngle-angle;if(dY>max)angle=viewAngle-max;else
if(dY<min)angle=viewAngle-min;}
v.rotate(i.center,_axis,-angle);}if(dX)v.rotate(i.center,[0,0,1],dX);this.setView(v);}}
iv.window.prototype.doDolly=function(dX,dY){var v=this.getView(),i=this.commonVPNotify("dolly",v,dX,dY),I=this.imp;if(v.ortho){var k=Math.max(1.0+(dY/100),1e-30);i.scale=v.scale/k;if(!this.notify("camera",i,true))return false;v.scale=i.scale;if(this.isCustomCenter(i,v)){var r0=this.getRay(I.x0,I.y0);this.setView(v);v.transform(vec3.subtract(r0,this.getRay(I.x0,I.y0)));}}else{var dir=vec3.subtract(v.from,i.center,[]),l=vec3.length(dir);i.len=Math.min(Math.max(l+l*dY/100,this.cfgMinDistance),this.cfgMaxDistance);if(!this.notify("camera",i,true))return false;var _dir=vec3.add(vec3.scale(dir,i.len/l,[]),i.center);var delta=vec3.subtract(_dir,v.from,[]);vec3.cpy(v.from,_dir);vec3.add(v.up,delta);if(this.isCustomCenter(i,v))vec3.add(v.to,delta);}this.setView(v);return true;}
iv.window.prototype.doFOV=function(dX,dY){var V=this.view,i={type:"fov",dX:dX,dY:dY,fov:Math.min(Math.max(V.fov+dY/8,1),175)};if((i.fov!=V.fov)&&this.notify("camera",i,true)){V.fov=i.fov;return true;}return false;}
iv.window.prototype.getRay=function(x,y,r){var w=this.viewport.x,h=this.viewport.y,v=this.view,p1=v.from,p2=v.to,dir=v.getViewVector(),up=v.getUpVector();vec3.normalize(up);var vx=vec3.crossN(dir,up,[]),h2=h/2,w2=w/2,i;if(!r)r=[];if(v.ortho){var dy=(h2-y)/h2,dx=(x-w2)/h2,k=1/v.scale;vec3.scale(vx,dx*k);vec3.scale(up,dy*k);for(i=0;i<3;i++)r[i]=p1[i]+up[i]+vx[i];}else{var k=vec3.length(dir)*Math.tan(this.getFOV(v)),ky=(h2-y)/h2,kx=(x-w2)/w2;vec3.scale(up,k*ky);vec3.scale(vx,k*kx*w/h);vec3.cpy(r,p1);}
for(i=0;i<3;i++)r[i+3]=p2[i]+up[i]+vx[i];return r;}
iv.context=function(wnd){if(wnd){this.window=wnd;this.space=wnd?wnd.space:null;this.bbScaleFactor=0.0;this.screenScale=0.0;this.view=new iv.viewInfo();this.version=-1;this.mvMatrix=mat4.create();this.itmw=1;}}
iv.context.prototype.addClip=function(node,a){}
iv.context.prototype.action=function(node,tm,state,opacity){return true;}
iv.context.prototype.getScaleFactor=function(unit){var k=this.bbScaleFactor;switch(unit){case 'pt':k*=1.512;break;case 'screen':k*=this.viewport.y/1000;break
case 'px':break;}return k;}
iv.context.prototype.update=function(utm){var w=this.window;if(this.version!=w.vpVersion){this.space=w.space;this.version=w.vpVersion;this.W2=this.viewport.x/2;this.H2=this.viewport.y/2;var v=w.view,up=v.getUpVector(),V=this.view;if(v.camera&&(v.camera.object instanceof iv.camera)){var cam=v.camera,wtm=cam.getWTM();cam=cam.object;if(wtm){mat4.mulPoint(wtm,cam.from,v.from);mat4.mulPoint(wtm,cam.to,v.to);mat4.mulPoint(wtm,cam.up,v.up);}else
{vec3.cpy(v.from,cam.from);vec3.cpy(v.to,cam.to);vec3.cpy(v.up,cam.up);}}this.ortho=!!v.ortho;if(v.ortho)this.screenScale=this.bbScaleFactor=1/(this.H2*v.scale);else{var fov=w.getFOV(v);this.bbScaleFactor=Math.tan(fov)/this.H2;this.screenScale=1.0/Math.tan(fov);if(utm){this.bbScaleFactor/=utm[0];this.screenScale/=utm[0];}}this.utm=utm;if(utm){mat4.lookAt(mat4.mulPoint(utm,v.from,V.from),mat4.mulPoint(utm,v.to,V.to),mat4.mulVector(utm,up,V.up),this.mvMatrix);mat4.mulPoint(utm,v.up,V.up);}
else mat4.lookAt(v.from,v.to,up,this.mvMatrix);if(!utm){vec3.cpy(V.from,v.from);vec3.cpy(V.to,v.to);vec3.cpy(V.up,v.up);}}return true;}
iv.context.prototype.viewToWorld=function(v,w){var W=this.W2,H=this.H2,k=this.screenScale,z=v[2];if(!w)w=[];if(this.ortho){w[0]=(v[0]-W)*k;w[1]=-(v[1]-H)*k;}else{w[1]=(z*(v[1]-H)/H)/k;w[0]=(-z*(v[0]-W)/H)/k;}
w[2]=z;if(!this.tmi)this.tmi=[];mat4.invert(this.tmi,this.mvMatrix);return mat4.mulPoint(this.tmi,w,w);}
iv.context.prototype.worldToView=function(w,v){v=mat4.mulPoint(this.mvMatrix,w,v);var z=v[2],W=this.W2,H=this.H2,k=this.screenScale;if(this.ortho){v[0]=v[0]/k+W;v[1]=-v[1]/k+H;return v;}if(z){v[0]=-(k*v[0]/z)*H+W;v[1]=(k*v[1]/z)*H+H;return v;}return null;}
iv.rcontext=function(wnd){iv.context.call(this,wnd);if(wnd){this.viewport=wnd.buffer;this.q=[];for(var i=1;i<12;i++)this.q[i]=({L:0,I:[]});this.tmTmp=mat4.create();this.itmw=0;}}
iv.rcontext.prototype=new iv.context(null);iv.rcontext.prototype.worldToView=function(w,v){var _w=w;if(this.utm)_w=mat4.mulPoint(this.utm,w,[]);return iv.context.prototype.worldToView.call(this,_w,v);}
iv.rcontext.prototype.action=function(n,a,b,c){if(n.object)return n.object.preRender(this,n,a,b,c);return true;}
iv.rcontext.prototype.getScaleFactor=function(unit){var k=iv.context.prototype.getScaleFactor.call(this,unit);k*=this.viewport.x/this.window.viewport.x;return k;};iv.queueItem=function(){this.tm=null;this.object=null;this.mtl=null;this.far=this.near=1.0;this.state=0;this.opacity=1.0;}
iv.rcontext.prototype.toRenderQueue=function(atm,node,state,opacity){var tm,i;if(atm)tm=mat4.m_z(atm,this.mvMatrix,this.tmTmp);else tm=this.mvMatrix;var obj=node.object,_min=obj.boxMin,_max=obj.boxMax,near=-(tm[2]*_min[0]+tm[6]*_min[1]+tm[10]*_min[2]),far=near,S=this.space;for(i=1;i<8;i++){var x=(i&1)?_max[0]:_min[0],y=(i&2)?_max[1]:_min[1],z=(i&4)?_max[2]:_min[2];z=-(tm[2]*x+tm[6]*y+tm[10]*z);if(z<near)near=z;else if(z>far)far=z;}
z=tm[14];far-=z;near-=z;if(far<1e-6)return;var rmode=S.rmodes[(state&0xff00)>>8],mtl=rmode.mtl||S.cfgDefMtl||node.material,s=node.stage||((mtl.opacity!=undefined||opacity<1.0)?4:2),_q=this.q[s],a=_q.I[_q.L];if(!a)a=_q.I[_q.L]=new iv.queueItem();a.tm=atm;a.object=obj;a.mtl=mtl;a.near=near;a.far=far;a.state=state|(node.state&iv.NS_MASK);a.opacity=opacity;_q.L++;}
iv.window.prototype.drawBk=function(s){var gl=this.gl,bk=this.cfgBkColor;gl.viewport(0,0,this.buffer.x,this.buffer.y);if(!s||!s.bk||(!s.drawBk())){if(!iv.isColor(bk))this.cfgBkColor=bk=iv.parseColor(bk);gl.clearColor(bk[0],bk[1],bk[2],1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);}}
iv.window.prototype.drawScene=function(){var s=this.space,l=this.layer;if(s){this.rcontext.update(s.unitMatrix);s.render(this.rcontext);}else this.drawBk(s);while(l){l.draw();l=l.nextLayer;}this.timer=false;if(this.postRepaint){this.invalidate();this.postRepaint=false;}if(s && !this.imp.numFrames++)this.notify('firstFrame');}
iv.window.prototype.invalidate=function(f){if(f!==undefined){if(f&iv.INV_VERSION)this.vpVersion++;if(f&iv.INV_STRUCTURE)this.structVersion++;if(f&iv.INV_MTLS && this.space)this.space.invalidateMaterials();}if(this.timer)return;this.timer=true;this.requestAnimFrame.call(window,this.drawScene.bind(this));}
iv.easeInOut=function(a){return 0.5+Math.sin((a-0.5)*Math.PI)/2;}
iv.window.prototype.animate=function(){var j=0,rez=0,uFlags=0,inv=false;var time=this.getTickCount(),_i=this.transitions;while(j<_i.length){var i=_i[j],del=false;if(i.lastTime!=time){if(i.duration){var a=(time-i.startTime)/i.duration;if((a>=1.0)||(a<0)){a=1.0;del=true;}if(i.transition)a=i.transition(a);rez=i.animate(a);}else
{rez=i.animate(Math.max(time-i.lastTime,0));if(!(rez&1))del=true;}
i.lastTime=time;}if(rez&2)inv=true;if(rez&4)uFlags|=iv.INV_VERSION;if(rez&16)uFlags|=iv.INV_STRUCTURE;if(del)this._removeAnimation(j,true);else j++;}if(inv)this.invalidate(uFlags);if(!_i.length){clearInterval(this.transTimer);this.transTimer=null;}}
iv.window.prototype.getAnimation=function(type){var _i=this.transitions,i,t;if(_i){for(i=0;i<_i.length;i++){t=_i[i];if(t.type && t.type==type)return i;}}return-1;};iv.window.prototype._removeAnimation=function(i,f){var _i=this.transitions,t=_i[i];if(t.detach)t.detach(this,f);if(t.type)this.notify("animend",{type:t.type,anim:t});_i.splice(i,1);}
iv.window.prototype.removeAnimationType=function(type,e){var _i=this.transitions,i,t;if(_i){for(i=0;i<_i.length;i++){t=_i[i];if(t.type && t.type==type){if(e && t.duration)t.animate(1.0);this._removeAnimation(i);return true;}}}return false;};iv.window.prototype.removeAnimation=function(a){var _i=this.transitions,i;if(_i){i=iv.indexOf(_i,a);if(i>-1){this._removeAnimation(i);return true;}}return false;}
iv.window.prototype.addAnimation=function(i){i.lastTime=this.getTickCount();if(i.duration)i.startTime=i.lastTime;if(!this.transitions)this.transitions=[];this.transitions.push(i);if(i.type)this.notify("animstart",{type:i.type,anim:i});if(!this.transTimer)this.transTimer=setInterval(this.input.a,10);return true;};iv.anim.spin=function(wnd,t,m){this.type="spin";this.wnd=wnd;var a=wnd.last,k=this.kf(a.dt)*wnd.cfgSpinSpeed;this.x=a.x*k;this.y=a.y*k;this.mode=m;}
iv.anim.spin.prototype.kf=function(a){return Math.pow(0.82,a/100);}
iv.anim.spin.prototype.animate=function(a){this.wnd.doOrbit(this.x,this.y);var k=this.kf(a);this.x*=k;this.y*=k;k=1e-1;if((Math.abs(this.x)<k)&&(Math.abs(this.y)<k)){return 6;}return 7;}
iv.window.prototype.stopAR=function(){this.removeAnimationType("spin");}
iv.window.prototype.setRMode=function(mode){var s=this.space;if(!s)return;var m=s.getRMode(mode);if(m && m.index!=s.cfgRMode){s.cfgRMode=m.index;this.invalidate();return true;}return false;}
iv.space=function(view,gl){this.gl=gl;this.window=view;this.spaceId=view.spaceId;view.spaceId++;this.activeShader=this.view=this.root=null;this.materials=[];this.shaders={v:[],p:[]};this.cfgDbl=this.cfgTextures=true;this.cfgKeepMeshData=3;this.cfgDefMtl=null;this.cfgSelZOffset=false;this.cfgRMode=0;this.clrSelection=view.clrSelection;this.stdLights=this.anySelection=false;this.extensions={};var w=0xffffffff,b=0xff000000;this.rmodes=[
{f:{n:true},name:"solid"},{f:null,e:{n:false,color:b},name:"wire"},{f:null,e:{n:true},name:"wireshaded"}
];this.lights=[];this.projectionTM=mat4.create();this.modelviewTM=mat4.create();this.meshesInQueue=0;if(gl){this.e_ans=(this.getExtension('EXT_texture_filter_anisotropic')||this.getExtension('MOZ_EXT_texture_filter_anisotropic')||this.getExtension('WEBKIT_EXT_texture_filter_anisotropic'));if(this.e_ans)this.e_ansMax=gl.getParameter(this.e_ans.MAX_TEXTURE_MAX_ANISOTROPY_EXT);}}
iv.space.prototype.getExtension=function(a){var e=this.gl.getExtension(a);if(!e && this.composeExtension){e=this.extensions[a];if(!e){e=this.composeExtension(a);if(e)this.extensions[a]=e;}}return e;}
iv.space.prototype.releaseShader=function(sh){sh.ref--;if(!sh.ref){var gl=this.gl,_i=(sh.type==gl.VERTEX_SHADER)?this.shaders.v:this.shaders.p,s;gl.deleteShader(sh.handle);sh.handle=null;var i=iv.indexOf(_i,sh);if(i>=0)_i.splice(i,1);}}
iv.space.prototype.getShader=function(str,type){var gl=this.gl,_i=(type==gl.VERTEX_SHADER)?this.shaders.v:this.shaders.p,s;for(var i=0;i<_i.length;i++){s=_i[i];if(s.str==str){s.ref++;return s;}}
var shader=gl.createShader(type),s={str:str,handle:shader,ref:1,type:type};_i.push(s);gl.shaderSource(shader,str);gl.compileShader(shader);if(!gl.getShaderParameter(shader,gl.COMPILE_STATUS)){var info=gl.getShaderInfoLog(shader);if(this.window)this.window.notify("error",{type:"compile",info:info,code:str});return null;}return s;}
iv.space.prototype.getSolidMaterial=function(c){c=iv.parseColor(c,true);var C=iv.ftoI(c[2])|(iv.ftoI(c[1])<<8)|(iv.ftoI(c[0])<<16),a=(c.length>3)?c[3]:1.0;C|=iv.ftoI(a)<<24;if(!this.solidMaterials)this.solidMaterials=[];var mtl=this.solidMaterials[C];if(!mtl){var data={emissive:{color:c}};if(a<1.0)data.opacity={amount:a};mtl=this.newMaterial(data);this.solidMaterials[C]=mtl;}return mtl;}
iv.space.prototype._checkRMMtl=function(m){if(m &&(m.color!==undefined)&&(!m.mtl))m.mtl=this.getSolidMaterial(m.color);}
iv.space.prototype.getRMode=function(mode){var L=this.rmodes,i,m;for(i=0;i<L.length;i++){m=L[i];if(m.name==mode){if(!m.l)m.l={mtl:null};this._checkRMMtl(m.f);this._checkRMMtl(m.l);this._checkRMMtl(m.e);if(m.index===undefined)m.index=i;return m;}}return null;}
iv.space.prototype.onMeshLoaded=function(m){this.meshesInQueue--;if(!this.meshesInQueue){var w=this.window;if(w && w.onMeshesReady)w.onMeshesReady(w,this);}this.invalidate(iv.INV_STRUCTURE);};iv.space.prototype.updateShadeArgs=function(a){var gl=this.gl,i,p=this.activeShader,ca=(p)?p.attrs.length:0,na=a?a.attrs.length:0;if(na>ca){for(i=ca;i<na;i++)gl.enableVertexAttribArray(i);}
else if(na<ca){for(i=na;i<ca;i++)gl.disableVertexAttribArray(i);}
ca=p?p.textures.length:0;for(i=0;i<ca;i++)p.textures[i].txt.unbind(i);}
iv.space.prototype.c1=function(s,info,flags){if(s!=this.activeShader)this.updateShadeArgs(s);if(s)s.activate(this,info,flags,s==this.activeShader);else this.gl.useProgram(null);this.activeShader=s;}
iv.space.prototype.c2=function(m,info,flags){var s=m?m.getShader(flags):0;if(s && !s.valid){if(this.activeShader)this.c1(null,null);s.update();}this.c1(s,info,flags);return s;}
iv.bk3d=function(space,txt){var gl=space.gl;this.uv=new Float32Array([0,0,1,0,0,1,0,1,1,0,1,1]);this.uvBuffer=iv.bufferF(gl,this.uv,2);this.vBuffer=iv.bufferF(gl,[-1.0,-1.0,0.0,1.0,-1.0,0.0,-1.0,1.0,0.0,-1.0,1.0,0.0,1.0,-1.0,0.0,1.0,1.0,0.0],3);var mtl=new iv.material(space);var d={wrapS:gl.CLAMP_TO_EDGE,wrapT:gl.CLAMP_TO_EDGE};if(typeof txt==='number')d.inline=txt;else d.texture=txt;mtl.load({emissive:d});this.mtl=mtl;this.texture=mtl.emissive[0].texture;}
iv.space.prototype.drawBk=function(){if(this.bk&&this.bk.texture.ready){var gl=this.gl,wnd=this.window;if(wnd.buffer.y&&wnd.buffer.x){gl.clear(gl.DEPTH_BUFFER_BIT);var bk=this.bk,b=null,w=512,h=512,img=bk.texture.image;if(img && img.naturalWidth)w=img.naturalWidth;else if(bk.texture.width)w=bk.texture.width;if(img && img.naturalHeight)h=img.naturalHeight;else if(bk.texture.height)h=bk.texture.height;var s=this.c2(bk.mtl,{opacity:1.0},2);for(var i=0;i<s.attrs.length;i++){var v=s.attrs[i];switch(v.id){case 4300: b=bk.vBuffer;gl.bindBuffer(gl.ARRAY_BUFFER,b);break;case 4302:{b=bk.uvBuffer;gl.bindBuffer(gl.ARRAY_BUFFER,b);}break;}if(b)gl.vertexAttribPointer(v.slot,b.itemSize,gl.FLOAT,false,0,0);}
gl.disable(gl.DEPTH_TEST);gl.depthMask(false);gl.drawArrays(gl.TRIANGLES,0,6);gl.enable(gl.DEPTH_TEST);gl.depthMask(true);return true;}}return false;}
iv.space.prototype.invalidate=function(f){this.window.invalidate(f);}
iv._handle_txt=function(i,t){t.notify("status");delete i.ivtexture;if(t.inline)URL.revokeObjectURL(i.src);}
iv.handleLoadedTexture=function(){var t=this.ivtexture,s=t.space;if(this.naturalWidth>0 && this.naturalHeight>0){t.bind().setImage(this);if(t.filter==iv.FILTER_MIPMAP)t.mipMap();t.unbind();}else t.error=true;iv._handle_txt(this,t);s.checkTextures();s.invalidate();}
iv.handleLoadedCubeTexture=function(){var t=this.ivtexture,s=t.space;t.bind().setImage(this,this.ivface).linear().unbind().numfaces++;if(t.numfaces==6){t.ready=true;s.checkTextures();s.invalidate();t.space=null;}
iv._handle_txt(this,t);};iv.space.prototype.checkTextures=function(){var _i=this.window.textures,l=0,f=0,i;for(i=0;i<_i.length;i++){var t=_i[i];if(t.ready||t.error)l++;if(t.error)f++;}this.window.notify('textures',{loaded:l,total:_i.length,failed:f,queue:_i.length-l});}
iv.space.prototype.getCubeInfo=function(){if(!this.cubeTexture){var gl=this.gl;this.cubeTexture=[{name:"posx",id:gl.TEXTURE_CUBE_MAP_POSITIVE_X,dir:[1,0,0],up:[0,-1,0]},{name:"negx",id:gl.TEXTURE_CUBE_MAP_NEGATIVE_X,dir:[-1,0,0],up:[0,-1,0]},{name:"posy",id:gl.TEXTURE_CUBE_MAP_POSITIVE_Y,dir:[0,1,0],up:[0,0,1]},{name:"negy",id:gl.TEXTURE_CUBE_MAP_NEGATIVE_Y,dir:[0,-1,0],up:[0,0,-1]},{name:"posz",id:gl.TEXTURE_CUBE_MAP_POSITIVE_Z,dir:[0,0,1],up:[0,-1,0]},{name:"negz",id:gl.TEXTURE_CUBE_MAP_NEGATIVE_Z,dir:[0,0,-1],up:[0,-1,0]}];}return this.cubeTexture;}
iv.space.prototype.getTexture=function(str,target,mtl){var t,_i=this.window.textures,gl=this.gl,i;for(i=0;i<_i.length;i++){t=_i[i];if((t.file==str)&&(t.target==target)){t.addRef();return t;}}
t=new iv.texture(gl,{target:target});t.space=this;t.file=str;var path=(mtl && mtl.path)?mtl.path:this.path;if(target==gl.TEXTURE_CUBE_MAP){var faces=this.getCubeInfo();t.numfaces=0;var _str=str.split(".");if(path)_str[0]=path+_str[0];for(i=0;i<6;i++){var f=faces[i],filename=_str[0]+f.name+"."+_str[1];this.loadTextureCube(t,f.id,filename);}}else{var _str=path?path+str:str;var e=iv.getExtension(str);if(str=='$(camera)'){if(iv.HandleCameraTexture)iv.HandleCameraTexture(t);}else
if(e=='MP4'||e=='WEBM'||e=='ogv'){if(iv.video)iv.video.initVideoTexture(t,_str);}else
this.loadTexture2d(t,_str);}
_i.push(t);return t;}
iv.space.prototype.newMaterial=function(n){var mtl=new iv.material(this),t=typeof n;this.materials.push(mtl);if(t=='string')mtl.name=name;else
if(t=='object')mtl.load(n);return mtl;}
iv.space.prototype.getBinData=function(b,i){return new Uint8Array(b,i.pos,i.szCmp);}
iv.space.prototype.loadBin=function(buffer){var data=new DataView(buffer),ms=[],is=[],l=data.byteLength,i=0,root=null,d;while(i<l){var id=data.getUint32(i,true),a=(id>>24)&0xff;d={pos:i+12,id:id,sz:data.getUint32(i+4,true),szCmp:data.getUint32(i+8,true)};if(a==2){d.format=data.getUint16(i+12,true);is[id&0xffffff]=d;}
else
if(a==1)ms[id&0xffffff]=d;else
if(id==0x746f6f72)root=d;i+=d.szCmp+12;}if(root){var _data=this.getBinData(buffer,root),text=ZIP.inflateStr(_data,root.sz),js=JSON.parse(text);if(js && js.space){for(i=1;i<is.length;i++)this.loadInlineTexture(data,is[i],i);d={objects:[],textures:is};l=ms.length;for(i=0;i<l;i++)d.objects.push(new iv.mesh(this.gl));this.loadImp(js,d);for(i=0;i<l;i++){var info=ms[i];d.objects[i].load(this,ZIP.inflateBin(this.getBinData(buffer,info),info.sz));}}}}
iv.space.prototype.loadTexture2d=function(t,url){var I=t.image=new Image;I.onload=iv.handleLoadedTexture;I.ivtexture=t;I.src=url;}
iv.space.prototype.loadTextureCube=function(t,id,url){var I=new Image;I.ivtexture=t;I.ivface=id;I.onload=iv.handleLoadedCubeTexture;I.src=url;}
iv.space.prototype.loadInlineTexture=function(data,info,index){var buffer=data.buffer,pos=info.pos+2,gl=this.gl,t=new iv.texture(gl);t.inline=true;t.file="?s"+this.spaceId+"i"+index;t.space=this;this.window.textures.push(t);var utype={type: info.format&1?'image\/jpeg':'image\/png'};if(info.format&0x100){t.numfaces=0;t.target=gl.TEXTURE_CUBE_MAP;var faces=this.getCubeInfo(),i;for(i=0;i<6;i++){var size=data.getUint32(pos,true);pos+=4;var view=new Uint8Array(buffer,pos,size);pos+=size;this.loadTextureCube(t,faces[i].id,URL.createObjectURL(new Blob([view],utype)));}}else this.loadTexture2d(t,URL.createObjectURL(new Blob([new Uint8Array(buffer,pos,info.szCmp-2)]),utype));}
iv.space.prototype.postProcessNode=function(n,d){n=n.firstChild;while(n){this.postProcessNode(n);n=n.next;}};iv.space.prototype.postProcess=function(d){if(this.root)this.postProcessNode(this.root)}
iv.space.prototype.loadImp=function(data,d){var s=data.space,i,a,c;d.materials=[];d.space=this;if(s.materials)for(i=0;i<s.materials.length;i++){var mtl=this.newMaterial(s.materials[i]);d.materials.push(mtl);}if(s.root){if(!this.root)this.root=new iv.node();this.root.load(s.root,d);}if(s.views){this.views=s.views;for(i=0;i<s.views.length;i++){var v=s.views[i];if(v.camera)v.camera=this.root.searchId(v.camera);}}if(s.anims){this.anims=s.anims;for(i=0;i<s.anims.length;i++){a=s.anims[i];if(a.active){this.activateAnimation(a);break;}}}
var tm=this.unitMatrix=mat4.identity(mat4.create());if(s.bbox){mat4.setScale(tm,s.bbox[0]);tm[12]=s.bbox[1];tm[13]=s.bbox[2];tm[14]=s.bbox[3];}if(s.view){a=s.view;c=this.view={from:a.from||a.org,to:a.to||a.target,up:a.up};if(a.fov)c.fov=a.fov;if(a.viewScale){c.scale=a.viewScale;c.ortho=true;}if(a.camera)c.camera=this.root.searchId(a.camera);if(a.bind)c.bind=a.bind;}
c=s.config;if(c){for(var v in c){switch(v){case "bkfaces":this.cfgDbl=c[v];break;}}}if(s.meta)this.meta=s.meta;this.postProcess(d);if(s.bkinline)this.bk=new iv.bk3d(this,s.bkinline);else
if(s.bk!=undefined)this.bk=new iv.bk3d(this,s.bk);}
iv.space.prototype.load=function(data){if(data && data.space){var m=data.space.meshes,d={objects:[]},i,obj;if(m)for(i=0;i<m.length;i++){obj=new iv.mesh(this.gl);if(this.path)obj.url=this.path+m[i].ref;else obj.url=m[i].ref;d.objects.push(obj);}this.loadImp(data,d);}};iv.space.prototype.renderQueue=function(items){var c=items.length,a,gl=this.gl,i,b,d;for(i=0;i<c;i++){b=items[i],d=(b.state&8)!=0;if(d!=a){if(d)gl.disable(gl.CULL_FACE);else gl.enable(gl.CULL_FACE);a=d;}
b.object.render(this,b);}}
iv.space.prototype.updatePrjTM=function(ctx){var wnd=this.window,V=wnd.view,gl=this.gl,ok=false,far=0,near=0,tm=this.projectionTM,kx;for(var iPass=1;iPass<ctx.q.length;iPass++){var q=ctx.q[iPass],c=q.L;if(!c)continue;var items=q.I,iO,d;for(iO=0;iO<c;iO++){d=items[iO];if(ok){if(d.near<near)near=d.near;if(d.far>far)far=d.far;}else{far=d.far;near=d.near;ok=true};}}
kx=ctx.viewport.x/ctx.viewport.y;if(V.ortho){var ky=1,scale=V.scale;if(this.unitMatrix)scale/=this.unitMatrix[0];kx/=scale;ky/=scale;mat4.ortho(-kx,kx,-ky,ky,near,far,tm);}else{var fov=wnd.getFOV(V);if(ok)mat4.perspectiveEx(fov,kx,near,far,tm);else mat4.perspective(fov,kx,0.1,100,tm);}}
iv.space.prototype.zCompareFunc=function(a,b){var _a=a ? a.near :-1e38,_b=b ? b.near :-1e38;if(_a > _b)return-1;if(_a<_b)return 1;return 0;}
iv.space.prototype.prepareLights=function(){var _i=this.lights,d=_i.length-this.currentLight,org=[0,0,0],i;if(d>0){_i.splice(this.currentLight,d);}
for(i=0;i<_i.length;i++){var l=_i[i],L=l.light;if(L.type!==l.type)l.type=L.type;l.color=L.color;if(L.type!=1){if(l.tm)l.org=mat4.mulPoint(l.tm,org,[]);else l.org=org;}if(L.target){if(!l.dir)l.dir=[];if(!l.targetNode||(L.target!=l.tagert))l.targetNode=this.root.searchId(l.tagert=L.target);if(l.targetNode){var wtm=l.targetNode.getWTM();if(wtm)mat4.getTranslate(wtm,l.dir);else vec3.cpy(l.dir,[0,0,0]);mat4.mulPoint(this.unitMatrix,l.dir,l.dir);vec3.subtractN(l.dir,l.org);}}else{var dir=L.dir;if(dir=="camera")l.dir=this.window.view.getViewVector(l.dir);else
if(l.tm){if(dir)l.dir=mat4.mulVector(l.tm,dir,[]);}else{if(dir)l.dir=dir.slice();}if(l.dir)vec3.normalize(l.dir);}if(l.type==2){if(!l.spot)l.spot=[0,0,0];var cin=Math.cos(L.inner/2),cout=Math.cos(L.outer/2);l.spot[0]=cin;l.spot[1]=cout;}}}
iv.space.prototype.invalidateMaterials=function(){var _i=this.materials,i;for(i=0;i<_i.length;i++)_i[i].invalidate();}
iv.space.prototype.render=function(ctx){if(this.root){mat4.copy(ctx.mvMatrix,this.modelviewTM);var gl=this.gl,astate=this.cfgRMode<<20,i,blend=false,q,L,_i;if(this.cfgDbl)astate|=8;this.currentLight=0;this.root.traverse(ctx,this.unitMatrix,astate,1.0);if(!this.stdLights)this.prepareLights();this.window.drawBk(this);gl.cullFace(gl.BACK);this.updatePrjTM(ctx);for(i=1;i<ctx.q.length;i++){q=ctx.q[i];L=q.L;if(!L)continue;_i=q.I;if(_i.length>q.L)_i.splice(q.L,_i.length-q.L);if(i>3){if(!blend){gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);blend=true;}if(i>=7)gl.clear(gl.DEPTH_BUFFER_BIT);_i.sort(this.zCompareFunc);}this.renderQueue(_i);q.L=0;}if(blend)gl.disable(gl.BLEND);this.c2(null);}}
iv.space.prototype.getMaterial=function(name){var it=this.materials,i,m;for(i=0;i<it.length;i++){m=it[i];if((m.name!==undefined)&&m.name==name)return m;}return null;}
;iv.mtlchannel=function(){this.mode=0;this.color=this.amount=null;this.texture=null;}
iv.mtlvar=function(id,n,t){this.id=id;this.name=n;this.type=t;this.slot=null;this.vertex=false;}
iv.shader=function(m,f){this.mtl=m;this.flags=f;this._reset();};iv.shader.prototype._reset=function(){this.valid=false;this.attrs=[];this.vars=[];this.textures=[];this.program=null;this.vShader=null;this.fShader=null;this.loadedtextures=0;this.numLights=0;}
iv.material=function(space){this.space=space;this.spaceId=space.spaceId;this.gl=space.gl;this.shaders=[];this.phong=18;}
iv.mtlchannel.prototype.setColor=function(clr){this.color=iv.parseColor(clr);}
iv.material.prototype.invalidate=function(){var s=this.shaders,i;if(s){for(i=0;i<s.length;i++)s[i].detach(this.gl);this.shaders=[];}}
iv.material.prototype.clear=function(){for(var i=0;i<iv.mtlChannels.length;i++){var c=iv.mtlChannels[i],ch=this[c];if(ch){for(var j=0;j<ch.length;j++){var item=ch[j];if(item.texture)item.texture.release();}
this[c]=null;}}}
iv.material.prototype.isChannel=function(c){if((c===undefined)||(c===null))return false;if(c.length===0)return false;for(var i=0;i<c.length;i++){var item=c[i];if(item.texture!=null||item.color!=null||item.amount!==null)return true;}return false;}
iv.material.prototype.newChannel=function(type,ch){if(!ch)ch=new iv.mtlchannel();if(!(type in this))this[type]=[];this[type].push(ch);this.valid=false;return ch;}
iv.material.prototype.getChannel=function(type){if(!(type in this))return null;var items=this[type];return items[0];}
iv.material.prototype.newTexture=function(c,name,type){var gl=this.gl;if(type===undefined)type=gl.TEXTURE_2D;c.texture=this.space.getTexture(name,type,this);if(type==gl.TEXTURE_CUBE_MAP)c.wrapT=c.wrapS=gl.CLAMP_TO_EDGE;else
{if(!c.wrapS)c.wrapS=gl.REPEAT;if(!c.wrapT)c.wrapT=gl.REPEAT;}}
iv.material.prototype.cnvTtxMatrix=function(a){var tm=mat3.create(),index=0,i,j;for(i=0;i<3;i++){for(j=0;j<2;j++){tm[i*3+j]=a[index];index++;}}
tm[2]=0;tm[5]=0;tm[8]=1;return tm;}
iv.material.prototype.loadChannelImp=function(v,name){var c=this.newChannel(name),t=v.texture;if(v.color!==undefined)c.setColor(v.color);if(v.amount!==undefined)c.amount=v.amount;if(v.blend)c.blend=v.blend;if(!t && v.inline)t="?s"+this.spaceId+"i"+v.inline;if(t!==undefined){var type;if(v.type&&v.type=="cube"){if(this.gl)type=this.gl.TEXTURE_CUBE_MAP;else type=0x8513;}if(v.tm)c.tm=this.cnvTtxMatrix(v.tm);if(v.cmp)c.cmp=v.cmp;if(v.filter)c.filter=v.filter;if(v.uvset)c.uv=v.uvset;else c.uv=0;if(v.wrapT)c.wrapT=v.wrapT;if(v.wrapS)c.wrapS=v.wrapS;if(v.format)c.format=v.format;this.newTexture(c,t,type);}}
iv.material.prototype.loadChannel=function(v,name){var type=typeof v;if(type==="number"){var c=this.newChannel(name);if(name=='opacity')c.amount=v;else c.setColor(v);}else
if(type==="object"){if(v instanceof Array){var len=v.length;if((len==3)&&(typeof v[0]=='number')&&(typeof v[1]=='number')&&(typeof v[2]=='number')){var c=this.newChannel(name);c.setColor(v);}else{for(var i=0;i<len;i++)this.loadChannelImp(v[i],name);}}else this.loadChannelImp(v,name);}};iv.material.prototype.load=function(d){for(var v in d){var a=d[v];switch(v){case "lightmap":
case "diffuse":
case "specular":
case "emissive":
case "reflection":
case "opacity":
case "bump":this.loadChannel(a,v);break;case "ambient":this.loadChannel(a,"emissive");break;case "meta":
case "name":
case "phong":
case "backSide":
case "path":this[v]=a;break;}}return true;}
iv.material.prototype.getShader=function(flags){if(!this.staticColors)flags&=~256;if(!this.space.cfgTextures)flags&=~(2|32);for(var i=0;i<this.shaders.length;i++){var s=this.shaders[i];if(s.flags==flags){if((s.loadedtextures!=s.textures.length)&& s.valid){var c=s.getNumTextures();if(c!=s.loadedtextures)s.valid=false;}if(s.numLights!=this.space.lights.length)s.valid=false;return s;}}
var s=new iv.shader(this,flags);this.shaders.push(s);return s;}
iv.shader.prototype.addVarying=function(name,type){this.t.varyings.push({name:name,type:type});}
iv.GLSLtype=function(a){switch(a){case 1:a="float";break;case 9:a="mat3";break;case 16:a="mat4";break;default:a="vec"+a;}return a;}
iv.shader.prototype.declareSome=function(_i,type){var s="",i,v;for(i=0;i<_i.length;i++){v=_i[i];s+=type+' '+iv.GLSLtype(v.type)+' '+v.name+';';}return s;}
iv.shader.prototype.insertVars=function(vt,ft){var _i=this.vars,c=_i.length,i,v,_v="",_f="",a;for(i=0;i<c;i++){v=_i[i];a="uniform "+iv.GLSLtype(v.type)+" "+v.name+";";if(v.vt)_v+=a;else _f+=a;}
a=this.declareSome(this.t.varyings,"varying");if(a.length){_v+=a;_f+=a;}
_v+=this.declareSome(this.attrs,"attribute");_i=this.textures;for(i=0;i<_i.length;i++){var t=_i[i];if(t.txt.ready){_f+="uniform "+(t.txt.isCube()?"samplerCube":"sampler2D")+" txtUnit"+t.slot+";";}}if(_v.length)vt.splice(0,0,_v);if(_f.length)ft.splice(0,0,_f);}
iv.shader.prototype.addU=function(id,name,t,vertex){var v=new iv.mtlvar(id,name,t);v.vt=!!(vertex);this.vars.push(v);return v;}
iv.shader.prototype.addAttr=function(id,name,t){this.attrs.push({id:id,name:name,type:t});}
iv.shader.prototype.addLightVar=function(id,name,light,t){var v=this.addU(id,name,t);v.light=light;return v;}
iv.shader.prototype.addChU=function(id,name,t,ch){var v=this.addU(id,name,t);v.channel=ch;return v;}
iv.shader.prototype.compareTM3=function(a,b){if(!a&& !b)return true;if(!a||!b)return false;for(var i=0;i<9;i++)if(Math.abs(a[i]-b[i])>1e-4)return false;return true;}
iv.shader.prototype.getTexture=function(c){var items=this.textures,j,t;for(j=0;j<items.length;j++){t=items[j];if(t.txt===c.texture &&(t.wrapS==c.wrapS)&&(t.wrapT==c.wrapT)&& this.compareTM3(t.tm,c.tm)&& c.uv==t.uv)return t;}return null;}
iv.shader.prototype.num=function(a){var t=a.toString();if(t.indexOf('.')<0)t+='.0';return t;}
iv.shader.prototype.num3=function(a){return "vec3("+this.num(a[0])+","+this.num(a[1])+","+this.num(a[2])+")";}
iv.shader.prototype.addAmount=function(c){if(this.mtl.staticColors)return this.num(c.amount);else return this.addChU(4104,"ch"+c._id+"amount",1,c).name;}
iv.shader.prototype.handleChannel_=function(gl,ch,ft){var text="",text2="",i,c;for(i=0;i<ch.length;i++){var c=ch[i],cname=null,tname=null,aname=null;c._id=this.channelId++;if(c.color!==null){if(this.mtl.staticColors){var clr=c.color;if(this.flags&256){var _s=this.mtl.space.clrSelection;clr=vec3.lerp(c.color,_s,_s[3]);}
cname=this.num3(clr);}else{cname="ch"+c._id+"clr";this.addChU(4102,cname,3,c);}}if(c.texture && c.texture.ready){var t=this.getTexture(c);if(t){if(c.texture.isCube()){text+="vec3 lup=reflect(eyeDirection,normal);lup.y*=-1.0;vec4 refColor="+"textureCube(txtUnit"+t.slot+",lup);";tname="refColor";}else{tname="txtColor"+t.slot;}}}if(tname && c.amount!==null)aname=this.addAmount(c);if(cname||tname){var local=null;if(aname && tname){local="vec3("+aname+")*vec3("+tname+")";if(cname)local+="*"+cname;}else
if(cname && tname)local=cname+"*vec3("+tname+")";else
if(cname)local=cname;else local="vec3("+tname+")";if(i && c.texture){if(c.format=='rgba'){if(aname)aname=aname+'*'+tname+'.a';else
aname=tname+'.a';}}if(text2.length){if(c.blend=='blend' && aname)text2="mix("+text2+","+local+','+aname+')';else
text2="("+text2+")"+this.getBlend(c)+local;}else text2=local;}}if(text.length)ft.push(text);return text2;}
iv.shader.prototype.handleChannel=function(gl,ch,cmp,ft){var text2=this.handleChannel_(gl,ch,ft);if(text2){if(cmp)text2=cmp+"*="+text2;else text2="color+="+text2;ft.push(text2+";");}if(cmp)ft.push("color+="+cmp+";");};iv.shader.prototype.getBlend=function(c){switch(c.blend){case "sub":return "-";case "mul":return "*";default:return "+";}}
iv.shader.prototype.handleAlphaChannel=function(gl,ch,ft){if(ch && ch.length){var txt=null,tAlpha=false;for(var i=0;i<ch.length;i++){var c=ch[i],tname=null,aname=null;c._id=this.channelId++;if(c.texture && c.texture.ready){var t=this.getTexture(c);if(t)tname="txtColor"+t.slot;}if(c.amount!==null)aname=this.addAmount(c);if(tname){if(aname)t=aname+"*";else t="";if(c.cmp && c.cmp=='a')t+=tname+".a";else
t+="("+tname+".x+"+tname+".y+"+tname+".z)/3.0";}else
if(aname)t=aname;if(t){if(txt){if(!tAlpha){txt="float alpha="+txt+";";tAlpha=true;}
txt+="alpha"+this.getBlend(c)+'='+t+";";}else txt=t;}}if(txt){if(tAlpha){ft.push(txt);return "alpha";}else return txt;}}return "1.0";}
iv.shader.prototype.handleBumpChannel=function(gl,ch){if(ch && ch.length){var c=ch[0];if(c.texture && c.texture.ready){c._id=this.channelId++;var t=this.getTexture(c);if(t){var tname="txtColor"+t.slot,text="vec3 _n=vec3("+tname+");";text+="_n-=vec3(0.5,0.5,0);_n*=vec3(2.0,2.0,1.0);";if(c.amount!==null){var aname=this.addAmount(c);text+="_n*=vec3("+aname+","+aname+",1.0);";}
text+="_n=normalize(_n);";return text;}}}return null;}
iv.shader.prototype.addTexture=function(t){this.textures.push(t);if(t.txt.ready){t.slot=this.loadedtextures;this.loadedtextures++;}return t;}
iv.shader.prototype.c0=function(ch,f){var rez=0,i,c,t;if(ch)for(i=0;i<ch.length;i++){c=ch[i];if(c.texture&&((f<0)||(f&(1<<c.uv)))){if(!this.getTexture(c)){t={txt:c.texture,wrapS:c.wrapS,wrapT:c.wrapT,uv:c.uv?c.uv:0};if(c.tm){t.tm=c.tm;t.ch=c;}this.addTexture(t);}if(c.texture.ready)rez|=1<<c.uv;}}return rez;}
iv.shader.prototype.getNumTextures=function(){var c=0,i,t;for(i=0;i<this.textures.length;i++){t=this.textures[i];if(t.txt.ready)c++;}return c;}
iv.shader.prototype.compile=function(i,type){return this.mtl.space.getShader(i.join('\r\n'),type);}
iv.shader.prototype.fetchTextures=function(gl,ft){var _i=this.textures,a=0,i,t,s;for(i=0;i<_i.length;i++){t=_i[i];if(t.txt.ready && t.txt.is2d()){if(t.tm){var v=this.addU(4103,"ch"+t.ch._id+"tm",9);v.channel=t.ch;s="_uv=vec2("+v.name+"*vec3(vUV"+t.uv+",1.0));";ft.push((a?"":"vec2 ")+s);a++;}
ft.push("vec4 txtColor"+t.slot+"=texture2D(txtUnit"+t.slot+","+((t.tm)?"_uv":"vUV"+t.uv)+");");}}}
iv.shader.prototype.addUVV=function(a,c,s){var S=s?3:2;this.addVarying("vUV"+(s?"Q":"")+a,S);this.addAttr(c,"inUV"+a,S);}
iv.shader.prototype.update=function(){var mtl=this.mtl,gl=mtl.gl,i,vt=[],ft=[],F=this.flags,space=mtl.space,lights=space.lights;if(this.program)this.detach(mtl.gl);this.numLights=lights.length;this.channelId=0;this.loadedtextures=0;this.t={varyings:[],ft:ft,vt:vt};var bN=(F&1)!=0,bSpecular=false,bDiffuse=false,bLights=false,bReflection=false,bBump=false,bLightMap=false;var bEmissive=mtl.isChannel(mtl.emissive);var bOpacity=mtl.isChannel(mtl.opacity)||(F&1024);this.addAttr(4300,"inV",3);if(F&8)this.addVarying("wPosition",4);if(F&4){this.addAttr(4305,"inC",3);this.addVarying("vC",3);}if(F&64){this.addAttr(4307,"inCE",3);this.addVarying("vCE",3);}if(bN){this.addVarying("wNormal",3);this.addAttr(4301,"inN",3);if(lights.length){bDiffuse=mtl.isChannel(mtl.diffuse);bSpecular=mtl.isChannel(mtl.specular);bLights=bDiffuse||bSpecular;}if(space.cfgTextures)bReflection=this.c0(mtl.reflection,-1);}
var UVF=0,bUV=0,UVQ0,UVQ1;if(F&2)UVF|=1;if(F&32)UVF|=2;if(UVF){if(bDiffuse)bUV|=this.c0(mtl.diffuse,UVF);if(bSpecular)bUV|=this.c0(mtl.specular,UVF);if(bEmissive)bUV|=this.c0(mtl.emissive,UVF);if(bOpacity)bUV|=this.c0(mtl.opacity,UVF);if(bN && bLights)bUV|=(bBump=this.c0(mtl.bump,UVF));bUV|=(bLightMap=this.c0(mtl.lightmap,UVF));}if(bUV&1)this.addUVV(0,4302,UVQ0=F&0x1000);if(bUV&2)this.addUVV(1,4306,UVQ1=F&0x2000);if(bBump){this.addVarying("vBN",3);this.addVarying("vBT",3);this.addAttr(4303,"inBN",3);this.addAttr(4304,"inBT",3);}
vt.push("void main(void){");if(F&8){vt.push("wPosition=tmWorld*vec4(inV,1.0);vec4 vPosition=tmModelView*");if(F&iv.R_Z_OFFSET){this.addU(4113,"veye",3,true);vt.push("(wPosition-vec4((wPosition.xyz-veye)/700.0,0.0));");}else vt.push("wPosition;");vt.push("gl_Position=tmPrj*vPosition;");this.addU(4101,"tmWorld",16,true);this.addU(4114,"tmModelView",16,true);this.addU(4115,"tmPrj",16,true);}
else vt.push("gl_Position=vec4(inV,1.0);");if(bN){vt.push("wNormal=");if(mtl.backSide)vt.push("-");vt.push("normalize(vec3(tmWorld*vec4(inN,0.0)));");}if(bBump)vt.push("vBN=normalize(vec3(tmWorld*vec4(inBN,0.0)));vBT=normalize(vec3(tmWorld*vec4(inBT,0.0)));");if(bUV&1)vt.push((UVQ0?"vUVQ0":"vUV0")+"=inUV0;");if(bUV&2)vt.push((UVQ1?"vUVQ1":"vUV1")+"=inUV1;");if(F&4)vt.push("vC=inC;");if(F&64)vt.push("vCE=inCE;");vt.push("}");if(bN){if(bSpecular)this.addU(4116,"mtlPhong",1);ft.push("float k;");}
ft.push("void main(void){");if(UVQ0)ft.push("vec2 vUV0=vec2(vUVQ0.x/vUVQ0.z,vUVQ0.y/vUVQ0.z);");if(UVQ1)ft.push("vec2 vUV1=vec2(vUVQ1.x/vUVQ1.z,vUVQ1.y/vUVQ1.z);");this.fetchTextures(gl,ft);if(bN){ft.push("vec3 normal=normalize(wNormal);");this.t.snormal="normal";var normalSign="";if(F&512){ft.push("vec3 normalSign=vec3(gl_FrontFacing?1.0:-1.0);");normalSign="normalSign*";}if(bBump){var txt=this.handleBumpChannel(gl,mtl.bump);if(txt){ft.push(txt);ft.push("mat3 tsM=mat3(normalize("+normalSign+"vBN),normalize("+normalSign+"vBT),normal);");ft.push("normal=normalize(tsM*_n);");}}if(F&512)ft.push("normal="+normalSign+"normal;");var veye=this.addU(4113,"eye",3);ft.push("vec3 eyeDirection=normalize(wPosition.xyz-eye),reflDir,posInLight;float specA,lightDistance,angle;");if(bLights){ft.push("vec3 diffuse,specular,lightDir;");for(i=0;i<lights.length;i++){var l=lights[i],aUsed=false;var vclr=this.addLightVar(4110,"light"+i+"Clr",l,3);var ls={light:l,vdir:null,vorg:null};var kstr="k*";if(l.dir)ls.vdir=this.addLightVar(4112,"light"+i+"Dir",l,3);if(l.org){if(l.org==='camera'){ls.vorg=eye;l.type=0;}else ls.vorg=this.addLightVar(4111,"light"+i+"Org",l,3);ls.dirName="lightDir";ft.push("posInLight=wPosition.xyz-"+ls.vorg.name+";lightDistance=length(posInLight);");ft.push("lightDir=posInLight/lightDistance;");}
switch(l.type){case 0:
break;case 1:ls.dirName=ls.vdir.name;break;case 2:
var vspot=this.addLightVar(4117,"light"+i+"Spot",l,3);ft.push("angle=smoothstep("+vspot.name+"[1],"+vspot.name+"[0],dot(lightDir,"+ls.vdir.name+"));");aUsed=true;break;}if(l.attenuation){var vatt=this.addLightVar(4118,"light"+i+"A",l,2),att;switch(l.light.light.attenuation){case "step":att="step(lightDistance,"+vatt.name+".x)";break;case "linear":att="(1.0-smoothstep("+vatt.name+".x,"+vatt.name+".y,lightDistance))";break;case "isquare":ft.push("lightDistance/="+vatt.name+".x;");att="1.0/(lightDistance*lightDistance)";break;}
ft.push((aUsed?"angle*=":"angle=")+att+";");aUsed=true;}if(aUsed)kstr="k*angle*";if(bSpecular){ft.push("reflDir=reflect(-"+ls.dirName+",normal);specA=dot(reflDir,eyeDirection);k=pow(max(specA,0.0),mtlPhong);");if(i)ft.push("specular+=");else ft.push("specular=");ft.push(kstr+vclr.name+";");}if(bDiffuse){ft.push("k=max(dot(normal,-"+ls.dirName+"),0.0);");if(i)ft.push("diffuse+=");else ft.push("diffuse=");ft.push(kstr+vclr.name+";");}}}}
ft.push("vec3 color=vec3(0.0);");if(F&4){if(bDiffuse &&(!(F&64)))ft.push("diffuse=diffuse*vC;");else
{ft.push("color+=vC;");bEmissive=false;}}if(F&64)ft.push("color+=vCE;");if(bDiffuse)this.handleChannel(gl,mtl.diffuse,"diffuse",ft);if(bSpecular)this.handleChannel(gl,mtl.specular,"specular",ft);if(bLightMap){var aoText=this.handleChannel_(gl,mtl.lightmap,ft);if(aoText)ft.push("color*="+aoText+";");}if(bEmissive)this.handleChannel(gl,mtl.emissive,null,ft);var alpha="1.0";if(bOpacity){var n;if(F&1024)this.addU(4106,"opacity",1);if(mtl.opacity){n=this.handleAlphaChannel(gl,mtl.opacity,ft);if(F&1024){ft.push("float _opacity=opacity*"+n+";");n="_opacity";}}else n="opacity";if(bReflection){var text2=this.handleChannel_(gl,mtl.reflection,ft);ft.push("vec3 _refColor="+text2+";");ft.push("float _refA=(_refColor.x+_refColor.y+_refColor.z)/3.0;");ft.push("_refA=1.0-(1.0-_refA)*(1.0-"+n+");");n="_refA";ft.push("color+=_refColor;");}else ft.push("if("+n+"<0.004)discard;");ft.push("gl_FragColor=vec4(color,"+n+");");}else{if(bReflection)this.handleChannel(gl,mtl.reflection,null,ft);ft.push("gl_FragColor=vec4(color,1.0);");}
ft.push("}");this.insertVars(vt,ft);ft.splice(0,0,"precision mediump float;");this.vShader=this.compile(vt,gl.VERTEX_SHADER);this.fShader=this.compile(ft,gl.FRAGMENT_SHADER);var shPrg=this.program=gl.createProgram();gl.attachShader(shPrg,this.vShader.handle);gl.attachShader(shPrg,this.fShader.handle);gl.linkProgram(shPrg);if(!gl.getProgramParameter(shPrg,gl.LINK_STATUS)){alert("Could not initialise shaders");}
gl.useProgram(shPrg);for(i=0;i<this.attrs.length;i++){var t=this.attrs[i];t.slot=gl.getAttribLocation(this.program,t.name);}
for(i=0;i<this.textures.length;i++){var t=this.textures[i];if(t.txt.ready)t.uniform=gl.getUniformLocation(shPrg,"txtUnit"+t.slot);}
i=0;while(i<this.vars.length){var v=this.vars[i];v.slot=gl.getUniformLocation(shPrg,v.name);if(!v.slot)this.vars.splice(i,1);else i++;}this.t=null;this.valid=true;return true;}
iv.shader.prototype.detach=function(gl){var p=this.program,v=this.vShader,f=this.fShader;if(p){gl.detachShader(p,v.handle);gl.detachShader(p,f.handle);gl.deleteProgram(p);this.mtl.space.releaseShader(v);this.mtl.space.releaseShader(f);}this._reset();}
iv.shader.prototype.activate=function(space,info,flags,newObj){var mtl=this.mtl,gl=mtl.gl,i;if(!newObj){gl.useProgram(this.program);for(i=0;i<this.textures.length;i++){var t=this.textures[i];if(t.txt.ready){t.txt.bind(t.slot);var type=t.txt.target;if(type==gl.TEXTURE_2D && space.e_ans &&(t.txt.filter==iv.FILTER_MIPMAP))gl.texParameterf(type,space.e_ans.TEXTURE_MAX_ANISOTROPY_EXT,space.e_ansMax);t.txt.wrap(t.wrapS,t.wrapT);gl.uniform1i(t.uniform,t.slot);}}}
var _i=this.vars;for(i=0;i<_i.length;i++){var a=_i[i],s=a.slot;switch(a.id){case 4101:gl.uniformMatrix4fv(s,false,info.tm);break;case 4102:{var c=a.channel.color;if(flags&256)c=vec3.lerp(c,space.clrSelection,space.clrSelection[3]);gl.uniform3fv(s,c);}break;case 4103:gl.uniformMatrix3fv(s,false,a.channel.tm);break;case 4104:gl.uniform1f(s,a.channel.amount);break;case 4106:gl.uniform1f(s,info.opacity);break;default:
if(!newObj){switch(a.id){case 4110:gl.uniform3fv(s,a.light.color);break;case 4111:gl.uniform3fv(s,a.light.org);break;case 4112:gl.uniform3fv(s,a.light.dir);break;case 4113:gl.uniform3fv(s,space.window.rcontext.view.from);break;case 4114:gl.uniformMatrix4fv(s,false,space.modelviewTM);break;case 4115:gl.uniformMatrix4fv(s,false,space.projectionTM);break;case 4116:gl.uniform1f(s,mtl.phong);break;case 4117:gl.uniform3fv(s,a.light.spot);break;case 4118:var k=(space && space.unitMatrix)?space.unitMatrix[0]:1.0;gl.uniform2f(s,k*a.light.light.innerRadius,k*a.light.light.outerRadius);break;}}}}}
;iv.node=function(){iv.abstract.call(this);this.object=null;this.tm=null;this.name="";this.material=null;this.state=0x303;this.wtm=[];}
iv.node.prototype=new iv.abstract();iv.node.prototype.newNode=function(){return this.insert(new iv.node());}
iv.node.prototype.insert=function(n){n.ref++;if(this.lastChild)this.lastChild.next=n;else this.firstChild=n;this.lastChild=n;n.parent=this;if(this.refTargets)this.notify("childadded",{child:n});return n;}
iv.node.prototype.removeAll=function(){while(this.firstChild)this.remove(this.firstChild);}
iv.node.prototype.destroy=function(){this.removeAll();this.setObject(null);if(this.refTargets)this.refTargets=null;}
iv.node.prototype.remove=function(n){if(n.parent!=this)return false;var _n=null;if(this.firstChild==n)this.firstChild=n.next;else
{_n=this.firstChild;while(_n){if(_n.next==n){_n.next=n.next;break;}
_n=_n.next;}}if(this.lastChild==n)this.lastChild=_n;n.parent=null;n.next=null;if(this.refTargets)this.notify("childremoved",{child:n});n.release();return true;}
iv.node.prototype.setState=function(s,mask){var _state=this.state&(~mask)|mask&s;if(_state!=this.state){s=this.state;this.state=_state;if(this.refTargets)this.notify("state",{old:s});return true;}return false;}
iv.node.prototype.traverse=function(ctx,ptm,flags,opacity){if(!(this.state&3))return;if(this.tm){if(ptm){var w=this.wtm,i=ctx.itmw;if(!w[i])w[i]=mat4.create();ptm=mat4.m(this.tm,ptm,w[i]);}else ptm=this.tm;};this.commonTraverse(ctx,ptm,flags,opacity);};iv.node.prototype.commonTraverse=function(ctx,ptm,flags,opacity){var m=this.rmode;if(m!==undefined){flags&=~0xff00000;if(typeof m=='string'){var M=ctx.space.getRMode(m);if(M){m=this.rmode=M.index<<20;}else{delete this.rmode;m=0;}}
flags|=m&0xff00000;}if(this.cull){if(this.cull===1)flags|=64;else flags&=~64;}if(this.opacity!==undefined && opacity!==undefined)opacity*=this.opacity;flags|=(this.state&4);if(this.state&1){m=opacity;if(!ctx.action(this,ptm,flags,opacity))return;}if(this.state&2){var a=this.firstChild;while(a){a.traverse(ctx,ptm,flags,opacity);a=a.next;}}}
iv.node.prototype.setObject=function(obj){if(this.object!=obj){if(this.object)this.object.release();this.object=obj;if(obj)obj.ref++;}}
iv.node.prototype.getBoundingBoxEmpty=function(tm,b,f){return b;}
iv.node.prototype.load=function(d,info){var i,j,a,v;for(v in d){a=d[v];switch(v){case 'light':this.setObject(new iv.light(a));break;case 'camera':this.setObject(new iv.camera(a));break;case 'object':this.setObject(info.objects[a]);break;case 'mtl':a=info.materials[a];if(a){this.material=a;if(a.bump && this.object)this.object.bump=true;}break;case 's':this.state=a^0x300;break;case 'tm':this.tm=iv.convertMatrix(d.tm);break;case 'i':for(i=0;i<a.length;i++)this.newNode().load(a[i],info);break;default:this[v]=a;}}}
iv.node.prototype.enableTM=function(){if(!this.tm)this.tm=mat4.identity(mat4.create());return this.tm;}
iv.node.prototype.getWTM=function(){var tm=null,n=this;while(n){if(n.tm){if(tm)mat4.m(tm,n.tm);else tm=mat4.create(n.tm);}
n=n.parent;}return tm;};iv.node.prototype.searchId=function(id){if(this.id==id)return this;var n=this.firstChild;while(n){var _n=n.searchId(id);if(_n)return _n;n=n.next;}return null;}
;iv.object=function(){iv.abstract.call(this);}
iv.object.prototype=new iv.abstract();iv.object.prototype.preRender=function(node,tm,space,state,opacity){return true;}
iv.object.prototype.hitTest=function(ctx,tm,node){return false;}
iv.object.prototype.preHitTest=function(ctx,tm){return false;}
iv.light=function(d){this.ref=0;this.type=0;this.dir=null;this.org=null;if(d)this.load(d);}
iv.light.prototype=new iv.object();iv.light.prototype.load=function(d){for(var v in d){var a=d[v];switch(v){case 'dir':
case 'org':this[v]=a.slice();break;default:this[v]=a;}}if(this.attenuation && !this.outerRadius)this.outerRadius=this.innerRadius;}
iv.light.prototype.preRender=function(ctx,node,tm,state,opacity){var space=ctx.space;if(!space.stdLights){var l=space.lights[space.currentLight];if(!l)space.lights.push(l={structVersion:-1});l.tm=tm;l.light=this;l.node=node;space.currentLight++;}return true;}
iv.camera=function(d){this.ref=0;this.perspective=false;if(d)this.load(d);}
iv.camera.prototype=new iv.object();iv.camera.prototype.load=function(d){for(var v in d){var a=d[v];switch(v){case 'from':
case 'up':
case 'to':this[v]=a.slice();break;default:this[v]=a;}}}
iv.camera.prototype.preRender=function(node,tm,space,state,opacity){return true;}
iv.mesh=function(gl){if(gl){iv.object.call(this);this.gl=gl;this.lineMode=false;}}
iv.mesh.prototype=new iv.object();iv.mesh.prototype.setPoints=function(a,keep){this.setBuffer('v',iv.bufferF(this.gl,a,3));if(keep)this.points=a;}
iv.mesh.prototype.setUV=function(a,keep,cmp){this.setBuffer('uv',iv.bufferF(this.gl,a,cmp||2));if(keep)this.uvpoints=a;}
iv.mesh.prototype.setUV2=function(a,keep,cmp){this.setBuffer('uv2',iv.bufferF(this.gl,a,cmp||2));if(keep)this.uv2points=a;}
iv.mesh.prototype.setNormals=function(a,keep){this.setBuffer('n',iv.bufferF(this.gl,a,3));if(keep)this.normals=a;}
iv.mesh.prototype.setFaces=function(f,keep){this.setBuffer('f',iv.bufferI(this.gl,f));if(keep)this.faces=f;}
iv.mesh.prototype.setBuffer=function(n,b){n+='Buffer';var _b=this[n];if(_b){_b.ref--;if(_b.ref<1)this.gl.deleteBuffer(_b);}
this[n]=b;if(b){if(b.ref)b.ref++;else b.ref=1;}}
iv.mesh.prototype.addEdge=function(e,v1,v2){if(v2>v1){var _v=v2;v2=v1;v1=_v;}if(e[v1]==undefined)e[v1]=v2;else
if(typeof e[v1]==='number')e[v1]=[e[v1],v2];else e[v1].push(v2);};iv.mesh.prototype.updateEdges=function(){if(!this.eBuffer){var f=this.faces;if(f){var nf=f.length/3,j=0,i,e=[];for(i=0;i<nf;i++){this.addEdge(e,f[j],f[j+1]);this.addEdge(e,f[j+1],f[j+2]);this.addEdge(e,f[j+2],f[j]);j+=3;}
var ne=e.length,num=0;for(i=0;i<ne;i++){var v=e[i];if(v!=undefined){if(typeof v==='number')num++;else num+=v.length;}}
var edges=new Uint16Array(num*2),v,i1;j=0;for(i=0;i<ne;i++){v=e[i];if(v!=undefined){if(typeof v==='number'){edges[j]=i;edges[j+1]=v;j+=2;}else
{for(i1=0;i1<v.length;i1++){edges[j]=i;edges[j+1]=v[i1];j+=2;}}}}this.setBuffer('e',iv.bufferI(this.gl,edges));}}return this.eBuffer;}
iv.mesh.prototype.preRender=function(ctx,node,tm,state,opacity){var space=ctx.space;if(this.url)iv.loadMesh(this,space);else{if(state&4){if(space.cfgSelZOffset)state|=0x20000;opacity*=space.clrSelection[4];}if(this.boxMin)ctx.toRenderQueue(tm,node,state,opacity);}return true;}
iv.mesh.prototype.c1=function(space,mtl,info,oz){if(!mtl)mtl=info.mtl;var s=space.c2(mtl,info,oz);var gl=space.gl;var _i=s.attrs,c=_i.length;for(var i=0;i<c;i++){var v=_i[i];var b=null,f=gl.FLOAT,n=false;switch(v.id){case 4300:b=this.vBuffer;break;case 4301:b=this.nBuffer;break;case 4302:b=this.uvBuffer;break;case 4306:b=this.uv2Buffer;break;case 4303:b=this.bnBuffer;break;case 4304:b=this.btBuffer;break;case 4305:b=this.cBuffer;f=gl.UNSIGNED_BYTE;n=true;break;case 4307:b=this.ceBuffer;f=gl.UNSIGNED_BYTE;n=true;break;}if(b){gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.vertexAttribPointer(v.slot,b.itemSize,f,n,0,0);}}}
iv.mesh.prototype.render=function(space,info){if(this.vBuffer){var state=info.state,gl=space.gl,f,F=8,fb=null;if(state&iv.R_Z_NOWRITE)gl.depthMask(false);var rm=space.rmodes[(state>>20)&0xff],m=rm.e,lm=this.lineMode,M=lm?(rm.l||rm.f):rm.f;if(m && !lm){f=F;fb=this.updateEdges(gl);if(fb){if(M)f|=iv.R_Z_OFFSET;if(this.nBuffer && m.n)f|=1;this.c1(space,m.mtl,info,f);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,fb);gl.drawElements(gl.LINES,fb.numItems,gl.UNSIGNED_SHORT,0);}}if(M){fb=this.fBuffer;if(fb){f=F;if(this.nBuffer && M.n)f|=1;if(this.uvBuffer){f|=2;if(this.uvBuffer.itemSize==3)f|=0x1000;}if(this.uv2Buffer){f|=32;if(this.uv2Buffer.itemSize==3)f|=0x2000;}if(this.cBuffer)f|=4;if(this.ceBuffer)f|=64;if(this.bnBuffer)f|=16;if(state&iv.R_SELECTION)f|=256;if(state&64)f|=512;if(info.opacity<1.0)f|=1024;f|=(state&(iv.R_Z_OFFSET));this.c1(space,M.mtl,info,f);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,fb);gl.drawElements(lm?gl.LINES:gl.TRIANGLES,fb.numItems,gl.UNSIGNED_SHORT,fb.offset||0);}}if(state&iv.R_Z_NOWRITE)gl.depthMask(true);}}
iv.bufferImp=function(gl,type,v,cmp,n){var b=gl.createBuffer();gl.bindBuffer(type,b);gl.bufferData(type,v,gl.STATIC_DRAW);b.itemSize=cmp;b.numItems=n;return b;}
iv.bufferF=function(gl,v,cmp){if((!(v instanceof Float32Array))&&(!(v instanceof Uint8Array)))v=new Float32Array(v);return iv.bufferImp(gl,gl.ARRAY_BUFFER,v,cmp,v.length/cmp);};iv.bufferI=function(gl,v){if(!(v instanceof Uint16Array))v=new Uint16Array(v);return iv.bufferImp(gl,gl.ELEMENT_ARRAY_BUFFER,v,1,v.length);}
iv.mesh.prototype.destroy=function(){this.setBuffer('uv',null);this.setBuffer('uv2',null);this.setBuffer('f',null);this.setBuffer('v',null);this.setBuffer('n',null);this.setBuffer('e',null);this.setBuffer('c',null);this.setBuffer('ce',null);this.setBuffer('bn',null);this.setBuffer('bt',null);}
iv.mesh.prototype.calcBBox=function(va){if(!va)va=this.points;if(!va)return;var count=va.length;if(count){var vminx=va[0],vminy=va[1],vminz=va[2];var vmaxx=vminx,vmaxy=vminy,vmaxz=vminz,p,i=3;while(i<count){p=va[i++];if(p<vminx)vminx=p;else if(p>vmaxx)vmaxx=p;p=va[i++];if(p<vminy)vminy=p;else if(p>vmaxy)vmaxy=p;p=va[i++];if(p<vminz)vminz=p;else if(p>vmaxz)vmaxz=p;}if(this.boxMin){this.boxMin[0]=vminx;this.boxMin[1]=vminy;this.boxMin[2]=vminz;}else this.boxMin=[vminx,vminy,vminz];if(this.boxMax){this.boxMax[0]=vmaxx;this.boxMax[1]=vmaxy;this.boxMax[2]=vmaxz;}else this.boxMax=[vmaxx,vmaxy,vmaxz];}}
;iv.loadMesh=function(m,s){var r=iv.createRequest(m.url,null,function(R){m.load(s,JSON.parse(R.responseText));s.onMeshLoaded(m);});if(r){s.meshesInQueue++;r.send();}delete m.url;}
iv.mesh.prototype.load=function(space,data){var gl=space.gl;if(data.vertexNormals)this.setNormals(data.vertexNormals,this.keepNormals);{var count=data.vertexPositions.length/3;var va=data.vertexPositions;this.setPoints(va,space.cfgKeepMeshData&2||this.keepPoints);var vminx=va[0],vminy=va[1],vminz=va[2];var vmaxx=vminx,vmaxy=vminy,vmaxz=vminz;for(var i=1;i<count;i++){var j=i*3;var p=va[j];if(p<vminx)vminx=p;else if(p>vmaxx)vmaxx=p;p=va[j+1];if(p<vminy)vminy=p;else if(p>vmaxy)vmaxy=p;p=va[j+2];if(p<vminz)vminz=p;else if(p>vmaxz)vmaxz=p;}this.boxMin=[vminx,vminy,vminz];this.boxMax=[vmaxx,vmaxy,vmaxz];}
var faces;if(data.indices)faces=data.indices;else
if(data.lines){faces=data.lines;this.lineMode=true;}if(faces)this.setFaces(faces,(space.cfgKeepMeshData&1));}
;iv.texture=function(gl,a){if(gl){iv.abstract.call(this);this.ref=1;this.gl=gl;this.target=gl.TEXTURE_2D;this.channels=gl.RGBA;this.type=gl.UNSIGNED_BYTE;this.width=this.height=0;this.filter=iv.FILTER_MIPMAP;this.ready=false;if(a){if(a.target)this.target=a.target;if(a.channels)this.channels=a.channels;if(a.type)this.type=a.type;}this.handle=gl.createTexture();}}
iv.texture.prototype=new iv.abstract();iv.texture.prototype.isCube=function(){return this.target==this.gl.TEXTURE_CUBE_MAP;}
iv.texture.prototype.is2d=function(){return this.target==this.gl.TEXTURE_2D;}
iv.texture.prototype.destroy=function(){if(this.handle){this.gl.deleteTexture(this.handle);this.handle=null;}this.ready=false;return this;};iv.texture.prototype._bind=function(unit,v){if(!unit)unit=0;this.gl.activeTexture(this.gl.TEXTURE0+unit);this.gl.bindTexture(this.target,v);return this;};iv.texture.prototype.bind=function(unit){return this._bind(unit,this.handle);};iv.texture.prototype.unbind=function(unit){return this._bind(unit,null);};iv.texture.prototype.setImage=function(img,i){var gl=this.gl;if(i===undefined)i=this.target;gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,this.is2d());gl.texImage2D(i,0,this.channels,this.channels,this.type,img);this.width=img.naturalWidth;this.height=img.naturalHeight;if(this.is2d())this.ready=true;return this;}
iv.texture.prototype.setSize=function(w,h){this.width=w;this.height=h;this.gl.texImage2D(this.target,0,this.channels,w,h,0,this.channels,this.type,null);return this;};iv.texture.prototype.setFilter=function(min,mag){if(!mag)mag=min;this.gl.texParameteri(this.target,this.gl.TEXTURE_MAG_FILTER,mag);this.gl.texParameteri(this.target,this.gl.TEXTURE_MIN_FILTER,min);return this;}
iv.texture.prototype.mipMap=function(){var pot=iv.isPOW2(this.width)&&iv.isPOW2(this.height),gl=this.gl,min=this.gl.LINEAR,max=pot?gl.LINEAR_MIPMAP_NEAREST:
this.setFilter(min,max);if(pot)gl.generateMipmap(this.target);return this;}
iv.texture.prototype.linear=function(){return this.setFilter(this.gl.LINEAR);};iv.texture.prototype.nearest=function(){return this.setFilter(this.gl.NEAREST);};iv.texture.prototype.wrap=function(s,t){if(!t)t=s;this.gl.texParameteri(this.target,this.gl.TEXTURE_WRAP_S,s);this.gl.texParameteri(this.target,this.gl.TEXTURE_WRAP_T,t);return this;}
iv.texture.prototype.clampToEdge=function(){this.wrap(this.gl.CLAMP_TO_EDGE);return this;};iv.texture.prototype.repeat=function(){this.wrap(this.gl.REPEAT);return this;};